package br.com.folhaconecta;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.test.context.ActiveProfiles; import org.springframework.transaction.annotation.Transactional;
import org.springframework.test.web.servlet.MockMvc; import org.springframework.mock.web.MockMultipartFile; import org.springframework.http.MediaType;
import tools.jackson.databind.ObjectMapper; import br.com.folhaconecta.folha.*; import br.com.folhaconecta.funcionario.Funcionario; import br.com.folhaconecta.ponto.dto.ResumoPonto;
import java.math.*; import java.time.*; import java.util.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*; import static org.junit.jupiter.api.Assertions.*;
@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("dev") @Transactional
class ApiIntegracaoTest {
 @Autowired MockMvc cliente; @Autowired ObjectMapper json; @Autowired TabelasFiscais tabelas; @Autowired CalculoFolhaService calculo;
 private String entrar(String login) throws Exception {var resposta=cliente.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(Map.of("tipo",login.contains("@")?"EMPRESA":"FUNCIONARIO","login",login,"senha","Demo@2026")))).andExpect(status().isOk()).andReturn().getResponse();return json.readTree(resposta.getContentAsString()).get("accessToken").asText();}
 @Test void loginRealJwtECookieSeguro() throws Exception {cliente.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"tipo\":\"EMPRESA\",\"login\":\"rh@demo.com\",\"senha\":\"Demo@2026\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.usuario.papeis[0]").value("RH")).andExpect(header().string("Set-Cookie",org.hamcrest.Matchers.allOf(org.hamcrest.Matchers.containsString("HttpOnly"),org.hamcrest.Matchers.containsString("SameSite=Strict"),org.hamcrest.Matchers.containsString("Path=/api/auth"))));}
 @Test void senhaErradaMensagemGenerica() throws Exception {cliente.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"tipo\":\"EMPRESA\",\"login\":\"rh@demo.com\",\"senha\":\"errada\"}")).andExpect(status().isUnauthorized()).andExpect(jsonPath("$.mensagem").value("Login ou senha invalidos"));}
 @Test void tokenObrigatorio() throws Exception {cliente.perform(get("/api/pendencias")).andExpect(status().isUnauthorized());}
 @Test void outraEmpresaNaoRevelaRegistros() throws Exception {String token=entrar("rh@demo.com");cliente.perform(get("/api/pendencias/8").header("Authorization","Bearer "+token)).andExpect(status().isNotFound());cliente.perform(get("/api/funcionarios/8").header("Authorization","Bearer "+token)).andExpect(status().isNotFound());}
 @Test void funcionarioVeSoSeusDadosENaoVeFolhaEquipe() throws Exception {String token=entrar("00000000001");cliente.perform(get("/api/pendencias").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.content[*].funcionarioId",org.hamcrest.Matchers.everyItem(org.hamcrest.Matchers.is(1))));cliente.perform(get("/api/pendencias/3").header("Authorization","Bearer "+token)).andExpect(status().isNotFound());cliente.perform(get("/api/folhas/2026-10/itens").header("Authorization","Bearer "+token)).andExpect(status().isForbidden());}
 @Test void rhNaoRecebeSalariosEFinanceiroRecebe() throws Exception {cliente.perform(get("/api/funcionarios").header("Authorization","Bearer "+entrar("rh@demo.com"))).andExpect(jsonPath("$.content[0].salarioBase").isEmpty());cliente.perform(get("/api/funcionarios").header("Authorization","Bearer "+entrar("financeiro@demo.com"))).andExpect(jsonPath("$.content[0].salarioBase").isNumber());}
 @Test void fluxoAtestadoHistoricoEPrivacidade() throws Exception {
  String funcionario=entrar("00000000001"),rh=entrar("rh@demo.com"),contabil=entrar("contabil@demo.com"),financeiro=entrar("financeiro@demo.com");
  var dados=new MockMultipartFile("dados","dados.json","application/json","{\"tipo\":\"ATESTADO\",\"titulo\":\"Atestado teste integrado\",\"dataInicio\":\"2026-10-19\",\"dataFim\":\"2026-10-20\"}".getBytes());var arquivo=new MockMultipartFile("arquivo","atestado.pdf","application/pdf","%PDF-1.4\nFicticio".getBytes());
  var criado=cliente.perform(multipart("/api/solicitacoes").file(dados).file(arquivo).header("Authorization","Bearer "+funcionario)).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("ABERTA")).andExpect(jsonPath("$.bloqueiaFolha").value(true)).andReturn().getResponse();var resultado=json.readTree(criado.getContentAsString());long id=resultado.get("id").asLong(),documento=resultado.get("documentos").get(0).get("id").asLong();
  cliente.perform(get("/api/documentos/"+documento+"/arquivo").header("Authorization","Bearer "+funcionario)).andExpect(status().isOk());cliente.perform(get("/api/documentos/"+documento+"/arquivo").header("Authorization","Bearer "+rh)).andExpect(status().isOk());cliente.perform(get("/api/documentos/"+documento+"/arquivo").header("Authorization","Bearer "+financeiro)).andExpect(status().isForbidden());
  mudar(id,rh,"EM_ANALISE","RH","Analise iniciada");mudar(id,rh,"CORRECAO_SOLICITADA","FUNCIONARIO","Documento ilegivel");
  cliente.perform(multipart("/api/pendencias/"+id+"/documentos").file(arquivo).header("Authorization","Bearer "+funcionario)).andExpect(status().isOk()).andExpect(jsonPath("$.setorResponsavel").value("RH")).andExpect(jsonPath("$.status").value("EM_ANALISE"));
  mudar(id,rh,"EM_ANALISE","CONTABILIDADE","Aprovado pelo RH");cliente.perform(get("/api/pendencias/"+id).header("Authorization","Bearer "+contabil)).andExpect(jsonPath("$.abonado").value(true)).andExpect(jsonPath("$.documentos").isEmpty());mudar(id,contabil,"CONCLUIDA","CONTABILIDADE","Conferencia concluida");
  cliente.perform(get("/api/pendencias/"+id+"/eventos").header("Authorization","Bearer "+funcionario)).andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(8));
 }
 private void mudar(long id,String token,String status,String setor,String comentario) throws Exception {cliente.perform(patch("/api/pendencias/"+id+"/status").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(Map.of("novoStatus",status,"proximoSetor",setor,"comentario",comentario)))).andExpect(status().isOk());}
 @Test void folhaBloqueiaEnvioEFechamento() throws Exception {cliente.perform(post("/api/folhas/2026-10/enviar-contabilidade").header("Authorization","Bearer "+entrar("financeiro@demo.com"))).andExpect(status().isConflict()).andExpect(jsonPath("$.bloqueios").isNotEmpty());cliente.perform(post("/api/folhas/2026-10/fechar").header("Authorization","Bearer "+entrar("contabil@demo.com"))).andExpect(status().isConflict());}
 @Test void folhaFechadaNaoRecalcula() throws Exception {cliente.perform(post("/api/folhas/2026-09/calcular").header("Authorization","Bearer "+entrar("financeiro@demo.com"))).andExpect(status().isConflict());}
 @Test void primeiroAcessoConsomeConvite() throws Exception {String rh=entrar("rh@demo.com");var criado=cliente.perform(post("/api/funcionarios").header("Authorization","Bearer "+rh).contentType(MediaType.APPLICATION_JSON).content("{\"nome\":\"Pessoa Teste\",\"cpf\":\"12345678901\",\"matricula\":\"TESTE\",\"cargo\":\"Analista\",\"departamento\":\"Teste\",\"salarioBase\":3000,\"cargaHorariaMensal\":220,\"dataAdmissao\":\"2026-10-01\",\"ativo\":true}")).andExpect(status().isOk()).andReturn().getResponse();String token=json.readTree(criado.getContentAsString()).get("convite").asText().split("token=")[1];String corpo=json.writeValueAsString(Map.of("token",token,"senha","Nova@2026"));cliente.perform(post("/api/auth/primeiro-acesso").contentType(MediaType.APPLICATION_JSON).content(corpo)).andExpect(status().isOk());cliente.perform(post("/api/auth/primeiro-acesso").contentType(MediaType.APPLICATION_JSON).content(corpo)).andExpect(status().isConflict());}
 @Test void refreshRotacionaERevogaAntigo() throws Exception {var login=cliente.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"tipo\":\"EMPRESA\",\"login\":\"rh@demo.com\",\"senha\":\"Demo@2026\"}")).andReturn().getResponse();var cookie=login.getCookie("refresh_token");cliente.perform(post("/api/auth/refresh").cookie(cookie)).andExpect(status().isOk());cliente.perform(post("/api/auth/refresh").cookie(cookie)).andExpect(status().isUnauthorized());}
 @Test void pontoAlternaEAudita() throws Exception {String token=entrar("00000000001");var entrada=cliente.perform(post("/api/ponto/registrar").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.entrada").isNotEmpty()).andExpect(jsonPath("$.saida").isEmpty()).andReturn().getResponse();long id=json.readTree(entrada.getContentAsString()).get("id").asLong();cliente.perform(post("/api/ponto/registrar").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.saida").isNotEmpty());cliente.perform(get("/api/ponto/"+id+"/eventos").header("Authorization","Bearer "+token)).andExpect(jsonPath("$.length()").value(2));cliente.perform(post("/api/ponto/registrar").header("Authorization","Bearer "+token)).andExpect(status().isConflict());}
 @Test void inssProgressivoETeto(){assertEquals(new BigDecimal("121.58"),tabelas.inss(new BigDecimal("1621")));assertEquals(new BigDecimal("164.68"),tabelas.inss(new BigDecimal("2100")));assertEquals(tabelas.inss(new BigDecimal("8475.55")),tabelas.inss(new BigDecimal("20000")));}
 @Test void irrfIsencaoEReducao2026(){assertEquals(new BigDecimal("0.00"),tabelas.irrf(new BigDecimal("4500"),new BigDecimal("5000")));var bruto=new BigDecimal("6000");assertEquals(new BigDecimal("385.10"),tabelas.irrf(bruto.subtract(tabelas.inss(bruto)),bruto));}
 @Test void calculoDinheiroEAbonoPorData(){var f=new Funcionario();f.setSalarioBase(new BigDecimal("2100"));f.setCargaHorariaMensal(220);var dia=LocalDate.of(2026,10,19);var resumo=new ResumoPonto(new BigDecimal("2"),2,List.of(dia,dia.plusDays(1)),List.of(dia.minusDays(3)));var item=calculo.calcular(f,resumo,Set.of(dia));assertEquals(new BigDecimal("28.64"),item.getValorHorasExtras());assertEquals(1,item.getDiasFalta());assertEquals(new BigDecimal("70.00"),item.getValorFaltas());assertEquals(new BigDecimal("126.00"),item.getValeTransporte());assertEquals(new BigDecimal("1771.68"),item.getLiquido());}
}
