services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: folhaconecta
      POSTGRES_USER: folha
      POSTGRES_PASSWORD: folha
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
