import { Component,effect,inject,signal,untracked } from '@angular/core'; import { CurrencyPipe,DecimalPipe } from '@angular/common'; import { DrawerModule } from 'primeng/drawer';
import { API } from '../../core/api/api.service'; import { AuthService } from '../../core/auth/auth.service'; import { UiService } from '../../core/ui.service'; import { Folha as Dados,ItemFolha,statusFolha } from '../../core/models/modelos';
import { PageHeader } from '../../shared/components/page-header'; import { Icone } from '../../shared/components/icone'; import { Skeleton,EmptyState } from '../../shared/components/estados'; import { FolhaStepper } from '../../shared/components/folha-stepper'; import { PendenciasTable } from '../../shared/components/pendencias-table'; import { Avatar } from '../../shared/components/badges';
@Component({selector:'fc-folha',imports:[CurrencyPipe,DecimalPipe,DrawerModule,PageHeader,Icone,Skeleton,EmptyState,FolhaStepper,PendenciasTable,Avatar],template:`
<fc-page-header titulo="Folha de pagamento" descricao="Uma prévia simples e transparente, conectada às pendências do mês.">@if(auth.setor()==='FINANCEIRO'){<button class="button primary" [disabled]="ocupado() || folha()?.status==='FECHADA' || folha()?.status==='EM_CONFERENCIA'" (click)="acao('calcular')"><fc-icon nome="calculator"/>{{ocupado()?'Processando…':'Calcular prévia'}}</button>}</fc-page-header>
@if(carregando()){<fc-skeleton/>}@else if(erro()){<div class="error-state" role="alert">{{erro()}}<button class="button" (click)="carregar()">Tentar de novo</button></div>}@else if(folha();as f){
<section class="card folha-overview"><div class="card-heading"><div><h2>{{mes()}}</h2><p>{{auth.usuario()?.empresa?.nome}}</p></div><span class="badge" [class.status-concluida]="f.status==='FECHADA'" [class.status-em_analise]="f.status!=='FECHADA'">{{statusFolha[f.status]}}</span></div><fc-folha-stepper [folha]="f"/><div class="folha-summary">@if(f.bloqueada){<span class="notice warning"><fc-icon nome="lock-keyhole"/>Bloqueada por {{f.bloqueios.length}} pendências</span>}@else{<span class="notice success"><fc-icon nome="circle-check"/>Sem pendências bloqueantes</span>}<div class="row-actions">@if(auth.setor()==='FINANCEIRO'){<button class="button" [disabled]="ocupado() || f.bloqueada || f.status!=='PREVIA_CALCULADA'" (click)="acao('enviar-contabilidade')">Enviar para a Contabilidade<fc-icon nome="arrow-right"/></button>@if(f.status==='FECHADA'){<button class="button primary" [disabled]="ocupado()" (click)="acao('publicar-holerites')">Publicar holerites</button>}}@if(auth.setor()==='CONTABILIDADE'){<button class="button primary" [disabled]="ocupado() || f.bloqueada || f.status!=='EM_CONFERENCIA'" (click)="acao('fechar')"><fc-icon nome="check"/>Conferir e fechar folha</button>}</div></div></section>
@if(f.bloqueada){<section class="card bloqueios-card"><div class="card-heading"><div><h2>O que impede o fechamento?</h2><p>Resolva cada pendência bloqueante antes de enviar ou fechar a folha.</p></div><span class="count-pill">{{f.bloqueios.length}}</span></div><fc-pendencias-table [itens]="f.bloqueios" (abrir)="ui.abrirPendencia($event)"/></section>}
@if(auth.tem('FINANCEIRO','CONTABILIDADE')){<section class="card"><div class="card-heading"><div><h2>Prévia por funcionário</h2><p>Clique em um funcionário para ver de onde veio cada valor.</p></div><span class="badge status-aberta">PRÉVIA</span></div>@if(!itens().length){<fc-empty titulo="A prévia ainda não foi calculada" descricao="O Financeiro calcula os valores depois da preparação do ponto e dos documentos."/>}@else{<div class="table-scroll"><table class="data-table payroll-table"><thead><tr><th>Funcionário</th><th>Salário base</th><th>Horas extras</th><th>Faltas</th><th>Descontos</th><th>Líquido</th><th>Situação</th></tr></thead><tbody>@for(item of itens();track item.id){<tr><td><button class="row-link person" (click)="abrir(item)"><fc-avatar [nome]="item.funcionarioNome" [pequeno]="true"/>{{item.funcionarioNome}}</button></td><td>{{item.salarioBase|currency:'BRL'}}</td><td>{{item.valorHorasExtras|currency:'BRL'}}<small>{{item.horasExtras|number:'1.2-2'}} h</small></td><td>{{item.valorFaltas|currency:'BRL'}}<small>{{item.diasFalta}} dias</small></td><td>{{item.inss+item.irrf+item.valeTransporte|currency:'BRL'}}</td><td><strong>{{item.liquido|currency:'BRL'}}</strong></td><td><span class="badge" [class.status-concluida]="item.situacao==='OK'" [class.status-correcao_solicitada]="item.situacao!=='OK'">{{item.situacao==='OK'?'OK':'Bloqueado'}}</span></td></tr>}</tbody><tfoot><tr><td colspan="5">Total líquido da prévia</td><td colspan="2">{{total()|currency:'BRL'}}</td></tr></tfoot></table></div>}</section><div class="notice neutral payroll-note"><fc-icon nome="info"/>Cálculo simplificado: salário + HE − faltas − INSS − IRRF − VT. Não inclui férias, 13º, rescisão, adicionais ou dependentes.</div>}
}
<p-drawer [visible]="!!selecionado()" (onHide)="selecionado.set(null)" position="right" header="Memória de cálculo" [style]="{width:'480px',maxWidth:'100vw'}">@if(selecionado();as item){<div class="drawer-content"><span class="badge status-aberta">PRÉVIA · {{item.competencia}}</span><h2>{{item.funcionarioNome}}</h2><p class="muted">Cada parcela e sua origem.</p><dl class="calculation"><dt>Salário base</dt><dd>{{item.salarioBase|currency:'BRL'}}</dd><dt>Horas extras · {{item.horasExtras|number:'1.2-2'}} h</dt><dd class="positive">+ {{item.valorHorasExtras|currency:'BRL'}}</dd><dt>Faltas · {{item.diasFalta}} dias</dt><dd>− {{item.valorFaltas|currency:'BRL'}}</dd><dt>INSS</dt><dd>− {{item.inss|currency:'BRL'}}</dd><dt>IRRF</dt><dd>− {{item.irrf|currency:'BRL'}}</dd><dt>Vale-transporte · 6%</dt><dd>− {{item.valeTransporte|currency:'BRL'}}</dd><dt class="calculation-total">Líquido</dt><dd class="calculation-total">{{item.liquido|currency:'BRL'}}</dd></dl><div class="memory-origin"><h3>Origem dos valores</h3>@for(linha of memoria();track linha.nome){<div><strong>{{linha.nome}}</strong><p>{{linha.valor}}</p></div>}</div></div>}</p-drawer>`})
export class Folha {
 readonly auth=inject(AuthService);readonly ui=inject(UiService);private api=inject(API);readonly statusFolha=statusFolha;readonly folha=signal<Dados|null>(null);readonly itens=signal<ItemFolha[]>([]);readonly selecionado=signal<ItemFolha|null>(null);readonly carregando=signal(true);readonly ocupado=signal(false);readonly erro=signal('');readonly memoria=signal<{nome:string;valor:string}[]>([]);
 constructor(){effect(()=>{this.ui.competencia();this.ui.versao();untracked(()=>void this.carregar());});}
 mes(){return new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(this.ui.competencia()+'-15T12:00:00'));}
 total(){return this.itens().reduce((s,i)=>s+i.liquido,0);}
 async carregar(){this.carregando.set(true);this.erro.set('');try{this.folha.set(await this.api.get<Dados>(`/folhas/${this.ui.competencia()}`));if(this.auth.tem('FINANCEIRO','CONTABILIDADE'))this.itens.set(await this.api.get<ItemFolha[]>(`/folhas/${this.ui.competencia()}/itens`));}catch(e){this.erro.set(this.ui.mensagem(e));}finally{this.carregando.set(false);}}
 async acao(acao:string){this.ocupado.set(true);try{this.folha.set(await this.api.post<Dados>(`/folhas/${this.ui.competencia()}/${acao}`));await this.carregar();this.ui.atualizar();this.ui.avisar({calcular:'Prévia calculada. Confira os valores e bloqueios.','enviar-contabilidade':'Folha enviada para conferência.',fechar:'Folha conferida e fechada.','publicar-holerites':'Holerites publicados para os funcionários.'}[acao]||'Folha atualizada.');}catch(e){this.ui.falhar(e);}finally{this.ocupado.set(false);}}
 async abrir(item:ItemFolha){try{const completo=await this.api.get<ItemFolha>(`/folhas/${item.competencia}/itens/${item.id}/memoria`);this.selecionado.set(completo);const m=JSON.parse(completo.memoriaCalculo) as Record<string,unknown>;this.memoria.set([{nome:'Horas extras',valor:`${m['formulaHorasExtras']||'Valores dos dados de demonstração'}. Datas: ${(m['datasExtras'] as string[]||[]).join(', ')||'Nenhuma'}`},{nome:'Faltas sem justificativa',valor:(m['datasFalta'] as string[]||[]).join(', ')||'Nenhuma falta não justificada.'},{nome:'Dias abonados pelo RH',valor:(m['diasAbonados'] as string[]||[]).join(', ')||'Nenhum afastamento aprovado no mês.'},{nome:'Tabela fiscal',valor:m['anoFiscal']?'Tabelas configuradas para '+m['anoFiscal']:'Valores ilustrativos do arquivo fornecido.'}]);}catch(e){this.ui.falhar(e);}}
}
