import { Component,effect,inject,signal,untracked } from '@angular/core'; import { FormsModule } from '@angular/forms'; import { DatePipe } from '@angular/common'; import { DialogModule } from 'primeng/dialog'; import { NgxMaskDirective } from 'ngx-mask';
import { API } from '../../core/api/api.service'; import { UiService } from '../../core/ui.service'; import { Funcionario,Pagina } from '../../core/models/modelos'; import { PageHeader } from '../../shared/components/page-header'; import { Icone } from '../../shared/components/icone'; import { Skeleton,EmptyState } from '../../shared/components/estados'; import { Avatar } from '../../shared/components/badges';
interface Cadastro { nome:string;cpf:string;matricula:string;cargo:string;departamento:string;salarioBase:number|null;cargaHorariaMensal:number;dataAdmissao:string;ativo:boolean; }
@Component({selector:'fc-funcionarios',imports:[FormsModule,DatePipe,DialogModule,NgxMaskDirective,PageHeader,Icone,Skeleton,EmptyState,Avatar],template:`
<fc-page-header titulo="Funcionários" descricao="Cadastros, acesso e informações da equipe em um só lugar."><button class="button primary" (click)="novo()"><fc-icon nome="user-round-plus"/>Cadastrar funcionário</button></fc-page-header><section class="card"><div class="filters"><label class="search-filter"><fc-icon nome="search"/><input [(ngModel)]="q" (ngModelChange)="carregar()" placeholder="Buscar nome ou matrícula" aria-label="Buscar funcionários"/></label><select [(ngModel)]="departamento" (ngModelChange)="carregar()" aria-label="Departamento"><option value="">Todos os departamentos</option>@for(d of departamentos();track d){<option [value]="d">{{d}}</option>}</select><span class="muted">{{itens().length}} funcionários</span></div>@if(carregando()){<fc-skeleton/>}@else if(erro()){<div class="error-state" role="alert">{{erro()}}<button class="button" (click)="carregar()">Tentar de novo</button></div>}@else if(!itens().length){<fc-empty titulo="Nenhum funcionário encontrado" descricao="Ajuste a busca ou cadastre o primeiro funcionário." acao="Cadastrar funcionário" (agir)="novo()"/>}@else{<div class="table-scroll"><table class="data-table"><thead><tr><th>Funcionário</th><th>Matrícula</th><th>Cargo / departamento</th><th>Admissão</th><th>Situação</th><th>Ação</th></tr></thead><tbody>@for(f of itens();track f.id){<tr><td><div class="person"><fc-avatar [nome]="f.nome" [pequeno]="true"/><strong>{{f.nome}}</strong></div></td><td>{{f.matricula}}</td><td>{{f.cargo}}<small>{{f.departamento}}</small></td><td>{{f.dataAdmissao|date:'dd/MM/yyyy'}}</td><td><span class="badge" [class.status-concluida]="f.ativo" [class.status-cancelada]="!f.ativo">{{f.ativo?'Ativo':'Inativo'}}</span></td><td><div class="row-actions"><button class="button small" (click)="editar(f)">Ver cadastro</button><button class="text-button" (click)="redefinir(f)">Gerar acesso</button></div></td></tr>}</tbody></table></div>}</section>
@if(convite()){<section class="card invite-card"><div><h3>Convite de acesso gerado</h3><p>Copie o link e compartilhe com o funcionário. Válido por 48 horas.</p></div><label>Link de primeiro acesso<input readonly [value]="convite()" aria-label="Link do convite"/></label><button class="button" (click)="copiar()"><fc-icon nome="copy"/>Copiar link</button></section>}
<p-dialog [header]="editando()?'Cadastro do funcionário':'Cadastrar funcionário'" [visible]="formAberto()" (visibleChange)="formAberto.set($event)" [modal]="true" [style]="{width:'600px',maxWidth:'96vw'}"><form (ngSubmit)="salvar()"><label>Nome completo<input name="nome" [(ngModel)]="form.nome" required/></label><div class="form-row"><label>CPF<input name="cpf" [(ngModel)]="form.cpf" mask="000.000.000-00" required/></label><label>Matrícula<input name="matricula" [(ngModel)]="form.matricula" required/></label></div><div class="form-row"><label>Cargo<input name="cargo" [(ngModel)]="form.cargo" required/></label><label>Departamento<input name="departamento" [(ngModel)]="form.departamento" required/></label></div><div class="form-row"><label>Admissão<input type="date" name="admissao" [(ngModel)]="form.dataAdmissao" required/></label><label>Carga mensal (horas)<input type="number" min="1" name="carga" [(ngModel)]="form.cargaHorariaMensal" required/></label></div>@if(!editando()){<label>Salário inicial (R$)<input type="number" min="0.01" step="0.01" name="salario" [(ngModel)]="form.salarioBase" required/></label>}<label class="checkbox"><input type="checkbox" name="ativo" [(ngModel)]="form.ativo"/>Funcionário ativo</label>@if(erroForm()){<p class="inline-error" role="alert">{{erroForm()}}</p>}<div class="form-footer"><button class="button" type="button" (click)="formAberto.set(false)">Cancelar</button><button class="button primary" [disabled]="ocupado()">{{ocupado()?'Salvando…':editando()?'Salvar cadastro':'Cadastrar e gerar convite'}}</button></div></form></p-dialog>`})
export class Funcionarios {
 private api=inject(API);readonly ui=inject(UiService);readonly itens=signal<Funcionario[]>([]);readonly departamentos=signal<string[]>([]);readonly carregando=signal(true);readonly erro=signal('');readonly erroForm=signal('');readonly ocupado=signal(false);readonly formAberto=signal(false);readonly editando=signal<number|null>(null);readonly convite=signal('');q='';departamento='';form:Cadastro=this.vazio();
 vazio():Cadastro{return{nome:'',cpf:'',matricula:'',cargo:'',departamento:'',salarioBase:null,cargaHorariaMensal:220,dataAdmissao:this.ui.hoje(),ativo:true};}
 constructor(){effect(()=>{this.ui.versao();untracked(()=>void this.carregar());});}
 async carregar(){this.carregando.set(true);this.erro.set('');try{const p=await this.api.get<Pagina<Funcionario>>('/funcionarios',{q:this.q,departamento:this.departamento,size:200});this.itens.set(p.content);if(!this.departamento)this.departamentos.set([...new Set(p.content.map(f=>f.departamento))]);}catch(e){this.erro.set(this.ui.mensagem(e));}finally{this.carregando.set(false);}}
 novo(){this.editando.set(null);this.form=this.vazio();this.erroForm.set('');this.formAberto.set(true);}
 async editar(f:Funcionario){try{const p=await this.api.get<Funcionario>(`/funcionarios/${f.id}`);this.editando.set(f.id);this.form={nome:p.nome,cpf:p.cpf,matricula:p.matricula,cargo:p.cargo,departamento:p.departamento,salarioBase:null,cargaHorariaMensal:p.cargaHorariaMensal,dataAdmissao:p.dataAdmissao,ativo:p.ativo};this.erroForm.set('');this.formAberto.set(true);}catch(e){this.ui.falhar(e);}}
 async salvar(){this.ocupado.set(true);this.erroForm.set('');try{if(this.editando())await this.api.put(`/funcionarios/${this.editando()}`,this.form);else{const p=await this.api.post<{funcionario:Funcionario;convite:string}>('/funcionarios',this.form);this.convite.set(location.origin+p.convite);}this.formAberto.set(false);await this.carregar();this.ui.avisar('Cadastro salvo.');}catch(e){this.erroForm.set(this.ui.mensagem(e));}finally{this.ocupado.set(false);}}
 async redefinir(f:Funcionario){try{const p=await this.api.get<Funcionario>(`/funcionarios/${f.id}`);if(!('usuarioId' in p)||!p.usuarioId){this.ui.avisar('Funcionário sem conta vinculada.');return;}const r=await this.api.post<{convite:string}>(`/usuarios/${p.usuarioId}/redefinir-senha`);this.convite.set(location.origin+r.convite);}catch(e){this.ui.falhar(e);}}
 async copiar(){try{await navigator.clipboard.writeText(this.convite());this.ui.avisar('Link copiado.');}catch{this.ui.avisar('Selecione o link acima para copiar.');}}
}
