create table empresa (
 id bigint generated by default as identity primary key,
 criado_em timestamp not null default current_timestamp,
 atualizado_em timestamp not null default current_timestamp,
 razao_social varchar(255),
 nome_fantasia varchar(255),
 cnpj varchar(255),
 dia_fechamento integer,
 unique(cnpj)
);
create table usuario (
 id bigint generated by default as identity primary key,
 criado_em timestamp not null default current_timestamp,
 atualizado_em timestamp not null default current_timestamp,
 nome varchar(255),
 email varchar(255),
 cpf varchar(255),
 senha_hash varchar(255),
 tipo_login varchar(255),
 ativo boolean,
 convite_hash varchar(255),
 convite_expira_em timestamp,
 unique(email),
 unique(cpf)
);
create table funcionario (
 id bigint generated by default as identity primary key,
 criado_em timestamp not null default current_timestamp,
 atualizado_em timestamp not null default current_timestamp,
 empresa_id bigint references empresa(id) not null,
 usuario_id bigint references usuario(id),
 nome varchar(255),
 cpf varchar(255),
 matricula varchar(255),
 cargo varchar(255),
 departamento varchar(255),
 salario_base numeric(12,2),
 carga_horaria_mensal integer,
 data_admissao date,
 ativo boolean,
 unique(empresa_id,cpf),
 unique(usuario_id)
);
create index idx_funcionario_empresa on funcionario(empresa_id);
create table pendencia (
 id bigint generated by default as identity primary key,
 criado_em timestamp not null default current_timestamp,
 atualizado_em timestamp not null default current_timestamp,
 empresa_id bigint references empresa(id) not null,
 funcionario_id bigint references funcionario(id),
 criado_por_id bigint references usuario(id),
 responsavel_id bigint references usuario(id),
 titulo varchar(255),
 descricao text,
 tipo varchar(255),
 status varchar(255),
 setor_responsavel varchar(255),
 setor_solicitante varchar(255),
 prazo date,
 competencia varchar(255),
 data_inicio date,
 data_fim date,
 bloqueia_folha boolean,
 abonado boolean
);
create index idx_pendencia_empresa on pendencia(empresa_id);
create table pendencia_evento (
 id bigint generated by default as identity primary key,
 criado_em timestamp not null default current_timestamp,
 atualizado_em timestamp not null default current_timestamp,
 empresa_id bigint references empresa(id) not null,
 pendencia_id bigint references pendencia(id),
 autor_id bigint references usuario(id),
 tipo varchar(255),
 status_anterior varchar(255),
 status_novo varchar(255),
 comentario text
);
create index idx_pendencia_evento_empresa on pendencia_evento(empresa_id);
create table documento (
 id bigint generated by default as identity primary key,
 criado_em timestamp not null default current_timestamp,
 atualizado_em timestamp not null default current_timestamp,
 empresa_id bigint references empresa(id) not null,
 pendencia_id bigint references pendencia(id),
 funcionario_id bigint references funcionario(id),
 enviado_por_id bigint references usuario(id),
 nome_original varchar(255),
 caminho_arquivo varchar(255),
 content_type varchar(255),
 tamanho_bytes bigint,
 sensivel boolean
);
create index idx_documento_empresa on documento(empresa_id);
create table registro_ponto (
 id bigint generated by default as identity primary key,
 criado_em timestamp not null default current_timestamp,
 atualizado_em timestamp not null default current_timestamp,
 empresa_id bigint references empresa(id) not null,
 funcionario_id bigint references funcionario(id),
 data date,
 entrada time,
 saida time,
 ajustado boolean,
 justificativa text,
 ajustado_por_id bigint references usuario(id),
 unique(empresa_id,funcionario_id,data)
);
create index idx_registro_ponto_empresa on registro_ponto(empresa_id);
create table folha (
 id bigint generated by default as identity primary key,
 criado_em timestamp not null default current_timestamp,
 atualizado_em timestamp not null default current_timestamp,
 empresa_id bigint references empresa(id) not null,
 competencia varchar(255),
 status varchar(255),
 calculada_em timestamp,
 fechada_em timestamp,
 fechada_por_id bigint references usuario(id),
 unique(empresa_id,competencia)
);
create index idx_folha_empresa on folha(empresa_id);
create table item_folha (
 id bigint generated by default as identity primary key,
 criado_em timestamp not null default current_timestamp,
 atualizado_em timestamp not null default current_timestamp,
 empresa_id bigint references empresa(id) not null,
 folha_id bigint references folha(id),
 funcionario_id bigint references funcionario(id),
 salario_base numeric(12,2),
 horas_extras numeric(12,2),
 valor_horas_extras numeric(12,2),
 dias_falta integer,
 valor_faltas numeric(12,2),
 inss numeric(12,2),
 irrf numeric(12,2),
 vale_transporte numeric(12,2),
 liquido numeric(12,2),
 memoria_calculo text,
 publicado boolean,
 unique(folha_id,funcionario_id)
);
create index idx_item_folha_empresa on item_folha(empresa_id);
create table notificacao (
 id bigint generated by default as identity primary key,
 criado_em timestamp not null default current_timestamp,
 atualizado_em timestamp not null default current_timestamp,
 empresa_id bigint references empresa(id) not null,
 usuario_id bigint references usuario(id),
 titulo varchar(255),
 mensagem text,
 link varchar(255),
 lida boolean
);
create index idx_notificacao_empresa on notificacao(empresa_id);
create table refresh_token (
 id bigint generated by default as identity primary key,
 criado_em timestamp not null default current_timestamp,
 atualizado_em timestamp not null default current_timestamp,
 empresa_id bigint references empresa(id) not null,
 usuario_id bigint references usuario(id),
 token_hash varchar(255),
 expira_em timestamp,
 revogado boolean
);
create index idx_refresh_token_empresa on refresh_token(empresa_id);
create table usuario_papel (usuario_id bigint not null references usuario(id), papel varchar(255) not null, primary key(usuario_id,papel));
create table usuario_empresa (usuario_id bigint not null references usuario(id), empresa_id bigint not null references empresa(id), primary key(usuario_id,empresa_id));
create index idx_pendencia_filtros on pendencia(empresa_id,status,prazo,competencia);
create index idx_evento_pendencia on pendencia_evento(empresa_id,pendencia_id);
create unique index idx_refresh_hash on refresh_token(token_hash);
create unique index idx_convite_hash on usuario(convite_hash) where convite_hash is not null;
