create table registro_ponto_evento (
 id bigint generated by default as identity primary key,
 criado_em timestamp not null default current_timestamp,
 atualizado_em timestamp not null default current_timestamp,
 empresa_id bigint not null references empresa(id),
 registro_id bigint not null references registro_ponto(id),
 autor_id bigint not null references usuario(id),
 entrada_anterior time, saida_anterior time, entrada_nova time, saida_nova time,
 justificativa text
);
create index idx_ponto_evento_empresa on registro_ponto_evento(empresa_id,registro_id);
-- Deixa o dia de referencia da demo disponivel para registrar entrada e saida.
delete from registro_ponto where data='2026-10-20' and ajustado=false;
