import { Component,effect,inject,signal,untracked } from '@angular/core'; import { FormsModule } from '@angular/forms'; import { ActivatedRoute,RouterLink } from '@angular/router';
import { PendenciasRestApi } from '../../core/api/pendencias.api'; import { API } from '../../core/api/api.service'; import { AuthService } from '../../core/auth/auth.service'; import { UiService } from '../../core/ui.service';
import { Funcionario,Pagina,Pendencia,setores,status,tipos } from '../../core/models/modelos'; import { PageHeader } from '../../shared/components/page-header'; import { Icone } from '../../shared/components/icone'; import { PendenciasTable } from '../../shared/components/pendencias-table'; import { Skeleton } from '../../shared/components/estados';
@Component({selector:'fc-central',imports:[FormsModule,RouterLink,PageHeader,Icone,PendenciasTable,Skeleton],template:`
<fc-page-header [titulo]="documentos?'Validação de documentos':'Central de Pendências'" [descricao]="documentos?'Confira os documentos enviados e encaminhe cada próximo passo.':'Tudo o que precisa ser resolvido, com responsável e prazo definidos.'">@if(auth.setor()!=='ADMIN'){<a class="button primary" [routerLink]="auth.setor()==='FUNCIONARIO'?'/solicitacoes/nova':'/pendencias/nova'"><fc-icon nome="plus"/>{{auth.setor()==='FUNCIONARIO'?'Nova solicitação':'Nova pendência'}}</a>}</fc-page-header>
<section class="card central-card"><div class="quick-tabs" role="tablist" aria-label="Filtrar pendências">@for(tab of abas;track tab.id){<button role="tab" [attr.aria-selected]="aba===tab.id" [class.ativa]="aba===tab.id" (click)="trocarAba(tab.id)">{{tab.nome}}@if(aba===tab.id){<span>{{total()}}</span>}</button>}</div>
<div class="filters"><label class="search-filter"><fc-icon nome="search"/><input [(ngModel)]="q" (ngModelChange)="buscar()" placeholder="Buscar título ou funcionário" aria-label="Buscar pendências"/></label><select [(ngModel)]="tipo" (ngModelChange)="filtrar()" aria-label="Tipo de pendência"><option value="">Todos os tipos</option>@for(t of chavesTipos;track t){<option [value]="t">{{tipos[t]}}</option>}</select><select [(ngModel)]="situacao" (ngModelChange)="filtrar()" aria-label="Status"><option value="">Todos os status</option>@for(s of chavesStatus;track s){<option [value]="s">{{status[s]}}</option>}</select><button class="button filter-toggle" (click)="maisFiltros=!maisFiltros"><fc-icon nome="sliders-horizontal"/>Filtros</button></div>
@if(maisFiltros){<div class="more-filters"><label>Setor responsável<select [(ngModel)]="setor" (ngModelChange)="filtrar()"><option value="">Todos os setores</option>@for(s of chavesSetores;track s){<option [value]="s">{{setores[s]}}</option>}</select></label>@if(auth.setor()!=='FUNCIONARIO'){<label>Funcionário<select [(ngModel)]="funcionarioId" (ngModelChange)="filtrar()"><option value="">Todos os funcionários</option>@for(f of funcionarios();track f.id){<option [value]="f.id">{{f.nome}}</option>}</select></label>}<label>Prazo a partir de<input type="date" [(ngModel)]="de" (ngModelChange)="filtrar()"/></label><label>Prazo até<input type="date" [(ngModel)]="ate" (ngModelChange)="filtrar()"/></label></div>}
@if(chips().length){<div class="filter-chips">@for(chip of chips();track chip.campo){<button (click)="remover(chip.campo)">{{chip.nome}}<fc-icon nome="x" [tamanho]="12"/></button>}<button class="clear-filters" (click)="limpar()">Limpar filtros</button></div>}
@if(carregando()){<fc-skeleton/>}@else if(erro()){<div class="error-state" role="alert">{{erro()}}<button class="button" (click)="carregar()">Tentar de novo</button></div>}@else{<fc-pendencias-table [itens]="itens()" (abrir)="ui.abrirPendencia($event)"/>}
<div class="pagination"><span>{{total()}} pendências · {{ui.competencia()}}</span><div><button class="button" [disabled]="pagina()===0 || carregando()" (click)="mudarPagina(-1)"><fc-icon nome="chevron-left"/>Anterior</button><span>{{pagina()+1}} de {{Math.max(1,paginas())}}</span><button class="button" [disabled]="pagina()+1>=paginas() || carregando()" (click)="mudarPagina(1)">Próxima<fc-icon nome="chevron-right"/></button></div></div></section>`})
export class Central {
 readonly auth=inject(AuthService);readonly ui=inject(UiService);private api=inject(API);private pendencias=inject(PendenciasRestApi);private route=inject(ActivatedRoute);
 readonly documentos=!!this.route.snapshot.data['documentos'];readonly tipos=tipos;readonly status=status;readonly setores=setores;readonly Math=Math;
 readonly chavesTipos=Object.keys(tipos) as (keyof typeof tipos)[];readonly chavesStatus=Object.keys(status) as (keyof typeof status)[];readonly chavesSetores=Object.keys(setores) as (keyof typeof setores)[];
 readonly abas=[{id:'comigo',nome:'Comigo'},{id:'todas',nome:'Todas'},{id:'atrasadas',nome:'Atrasadas'},{id:'semana',nome:'Vencem esta semana'},{id:'concluidas',nome:'Concluídas'}];
 aba='comigo';q='';tipo=this.documentos?'ATESTADO':'';situacao='';setor='';funcionarioId='';de='';ate='';maisFiltros=false;private timer?:ReturnType<typeof setTimeout>;
 readonly itens=signal<Pendencia[]>([]);readonly funcionarios=signal<Funcionario[]>([]);readonly total=signal(0);readonly paginas=signal(0);readonly pagina=signal(0);readonly carregando=signal(true);readonly erro=signal('');
 constructor(){this.route.queryParamMap.subscribe(params=>{this.aba=params.get('aba')||'comigo';this.q=params.get('q')||'';this.situacao=params.get('status')||'';this.pagina.set(0);void this.carregar();const id=params.get('pendencia');if(id)this.ui.abrirPendencia(Number(id));});effect(()=>{this.ui.versao();this.ui.competencia();untracked(()=>void this.carregar());});if(this.auth.setor()!=='FUNCIONARIO')void this.api.get<Pagina<Funcionario>>('/funcionarios',{size:200}).then(p=>this.funcionarios.set(p.content)).catch(e=>this.ui.falhar(e));}
 chips(){return [{campo:'q',nome:this.q?'Busca: '+this.q:''},{campo:'tipo',nome:this.tipo?tipos[this.tipo as keyof typeof tipos]:''},{campo:'situacao',nome:this.situacao?status[this.situacao as keyof typeof status]:''},{campo:'setor',nome:this.setor?setores[this.setor as keyof typeof setores]:''},{campo:'funcionarioId',nome:this.funcionarioId?this.funcionarios().find(f=>f.id===+this.funcionarioId)?.nome||'Funcionário':''},{campo:'de',nome:this.de?'A partir de '+this.de:''},{campo:'ate',nome:this.ate?'Até '+this.ate:''}].filter(c=>c.nome);}
 remover(campo:string){if(campo==='q')this.q='';if(campo==='tipo')this.tipo='';if(campo==='situacao')this.situacao='';if(campo==='setor')this.setor='';if(campo==='funcionarioId')this.funcionarioId='';if(campo==='de')this.de='';if(campo==='ate')this.ate='';this.filtrar();}
 limpar(){this.q=this.tipo=this.situacao=this.setor=this.funcionarioId=this.de=this.ate='';this.filtrar();}
 trocarAba(aba:string){this.aba=aba;this.situacao='';this.filtrar();}
 buscar(){clearTimeout(this.timer);this.timer=setTimeout(()=>this.filtrar(),250);}
 filtrar(){this.pagina.set(0);void this.carregar();}mudarPagina(n:number){this.pagina.update(p=>p+n);void this.carregar();}
 async carregar(){this.carregando.set(true);this.erro.set('');try{const semana=new Date(this.ui.hoje()+'T12:00:00');semana.setDate(semana.getDate()+6);const p=await this.pendencias.listar({page:this.pagina(),size:20,sort:'prazo,asc',competencia:this.ui.competencia(),q:this.q||undefined,tipo:this.tipo||undefined,status:this.aba==='concluidas'?'CONCLUIDA':this.situacao||undefined,setor:this.setor||undefined,funcionarioId:this.funcionarioId?+this.funcionarioId:undefined,comigo:this.aba==='comigo'||undefined,atrasadas:this.aba==='atrasadas'||undefined,de:this.aba==='semana'?this.ui.hoje():this.de||undefined,ate:this.aba==='semana'?semana.toISOString().slice(0,10):this.ate||undefined});this.itens.set(p.content);this.total.set(p.totalElements);this.paginas.set(p.totalPages);}catch(e){this.erro.set(this.ui.mensagem(e));}finally{this.carregando.set(false);}}
}
