import { Component,inject,signal } from '@angular/core'; import { FormsModule } from '@angular/forms'; import { Router,RouterLink,ActivatedRoute } from '@angular/router';
import { API } from '../../core/api/api.service'; import { AuthService } from '../../core/auth/auth.service'; import { UiService } from '../../core/ui.service'; import { Funcionario,Pagina,Pendencia,tipos,setores } from '../../core/models/modelos';
import { PageHeader } from '../../shared/components/page-header'; import { Icone } from '../../shared/components/icone'; import { UploadDropzone } from '../../shared/components/upload-dropzone';
@Component({selector:'fc-nova-pendencia',imports:[FormsModule,RouterLink,PageHeader,Icone,UploadDropzone],template:`
<fc-page-header [titulo]="funcionario?'Enviar uma solicitação':'Nova pendência'" [descricao]="funcionario?'Envie seu documento. O RH acompanha a análise e os próximos passos.':'Defina o que precisa ser resolvido, por quem e até quando.'"/>
@if(enviado();as p){<section class="card confirmation"><span class="confirmation-icon"><fc-icon nome="circle-check" [tamanho]="44"/></span><h2>{{funcionario?'Enviado ao RH.':'Pendência criada.'}}</h2><p>{{funcionario?'Prazo de análise: 2 dias úteis. Você pode acompanhar cada atualização na Central de Pendências.':'O setor responsável foi notificado. O histórico já está disponível.'}}</p><span class="muted">Solicitação #{{p.id}} · {{p.titulo}}</span><button class="button primary" (click)="acompanhar(p.id)">Acompanhar solicitação<fc-icon nome="arrow-right"/></button></section>}
@else{<div class="form-layout"><form class="card request-form" (ngSubmit)="enviar()"><div class="card-heading"><h2>{{funcionario?'Como podemos ajudar?':'Dados da pendência'}}</h2><fc-icon nome="file-plus-2"/></div><div class="form-body">
<label>Tipo de solicitação<select name="tipo" [(ngModel)]="tipo">@for(t of chavesTipos;track t){<option [value]="t">{{tipos[t]}}</option>}</select></label><label>Título<input name="titulo" [(ngModel)]="titulo" required maxlength="120" placeholder="Ex.: Atestado de afastamento"/></label>
@if(!funcionario){<label>Funcionário<select name="funcionario" [(ngModel)]="funcionarioId" required><option value="">Selecione o funcionário</option>@for(f of funcionarios();track f.id){<option [value]="f.id">{{f.nome}}</option>}</select></label><div class="form-row"><label>Setor responsável<select name="setor" [(ngModel)]="setor">@for(s of chavesSetores;track s){<option [value]="s">{{setores[s]}}</option>}</select></label><label>Prazo<input type="date" name="prazo" [(ngModel)]="prazo" [min]="ui.hoje()" required/></label></div>}
@if(tipo==='ATESTADO' || tipo==='FERIAS'){<div class="form-row"><label>Data inicial<input type="date" name="inicio" [(ngModel)]="inicio" required/></label><label>Data final<input type="date" name="fim" [(ngModel)]="fim" [min]="inicio" required/></label></div>}
@if(funcionario){<label>Documento {{tipo==='ATESTADO'?'*':'(opcional)'}}</label><fc-upload [arquivo]="arquivo()" (mudou)="selecionar($event)"/>}<label>{{funcionario?'Observação (opcional)':'Descrição'}}<textarea name="observacao" [(ngModel)]="observacao" rows="4" maxlength="4000" placeholder="Conte o que o responsável precisa saber…"></textarea></label>
@if(!funcionario){<label class="checkbox"><input type="checkbox" name="bloqueia" [(ngModel)]="bloqueia"/>Esta pendência bloqueia o fechamento da folha</label>}
@if(erro()){<p class="inline-error" role="alert">{{erro()}}</p>}<div class="form-footer"><a routerLink="/pendencias" class="button">Cancelar</a><button class="button primary" [disabled]="ocupado()"><fc-icon nome="send"/>{{ocupado()?'Enviando…':funcionario?'Enviar ao RH':'Criar pendência'}}</button></div></div></form>
<aside class="card form-help"><span class="action-icon"><fc-icon nome="shield-check" [tamanho]="26"/></span><h3>Clareza em cada etapa</h3><p>O responsável recebe uma notificação. Você acompanha a análise, os pedidos de correção e a conclusão.</p><hr/><h4>Quem pode ver meu atestado?</h4><p>O arquivo só pode ser aberto por você e pelo RH. Os demais setores recebem o resultado da análise.</p><span class="muted">Arquivos de até 5 MB.</span></aside></div>}`})
export class NovaPendencia {
 readonly auth=inject(AuthService);readonly ui=inject(UiService);private api=inject(API);private router=inject(Router);readonly funcionario=this.auth.setor()==='FUNCIONARIO';readonly tipos=tipos;readonly setores=setores;
 readonly chavesTipos=(Object.keys(tipos) as (keyof typeof tipos)[]).filter(t=>!this.funcionario||['ATESTADO','FERIAS','ALTERACAO_CADASTRAL','DUVIDA'].includes(t));readonly chavesSetores=['FUNCIONARIO','RH','FINANCEIRO','CONTABILIDADE'] as const;
 tipo='ATESTADO';titulo='';inicio=this.ui.hoje();fim=this.ui.hoje();observacao='';funcionarioId='';setor='RH';prazo=this.ui.hoje();bloqueia=true;readonly arquivo=signal<File|null>(null);readonly funcionarios=signal<Funcionario[]>([]);readonly ocupado=signal(false);readonly erro=signal('');readonly enviado=signal<Pendencia|null>(null);
 constructor(){const tipoInicial=inject(ActivatedRoute).snapshot.queryParamMap.get('tipo');if(this.chavesTipos.includes(tipoInicial as keyof typeof tipos))this.tipo=tipoInicial!;if(!this.funcionario)void this.api.get<Pagina<Funcionario>>('/funcionarios',{size:200}).then(p=>this.funcionarios.set(p.content)).catch(e=>this.ui.falhar(e));}
 selecionar(arquivo:File){if(arquivo.size>5*1024*1024||!/\.(pdf|png|jpe?g)$/i.test(arquivo.name)){this.erro.set('Envie um PDF, PNG ou JPEG de até 5 MB.');return;}this.arquivo.set(arquivo);this.erro.set('');}
 async enviar(){if(this.tipo==='ATESTADO'&&this.funcionario&&!this.arquivo()){this.erro.set('Selecione o arquivo do atestado.');return;}if(this.fim<this.inicio){this.erro.set('A data final deve ser igual ou posterior à inicial.');return;}this.ocupado.set(true);this.erro.set('');try{let p:Pendencia;if(this.funcionario){const dados=new FormData();dados.append('dados',new Blob([JSON.stringify({tipo:this.tipo,titulo:this.titulo,dataInicio:['ATESTADO','FERIAS'].includes(this.tipo)?this.inicio:null,dataFim:['ATESTADO','FERIAS'].includes(this.tipo)?this.fim:null,observacao:this.observacao})],{type:'application/json'}));if(this.arquivo())dados.append('arquivo',this.arquivo()!);p=await this.api.post<Pendencia>('/solicitacoes',dados);}else p=await this.api.post<Pendencia>('/pendencias',{funcionarioId:+this.funcionarioId,titulo:this.titulo,descricao:this.observacao,tipo:this.tipo,setorResponsavel:this.setor,prazo:this.prazo,competencia:this.ui.competencia(),dataInicio:['ATESTADO','FERIAS'].includes(this.tipo)?this.inicio:null,dataFim:['ATESTADO','FERIAS'].includes(this.tipo)?this.fim:null,bloqueiaFolha:this.bloqueia});this.enviado.set(p);this.ui.atualizar();}catch(e){this.erro.set(this.ui.mensagem(e));}finally{this.ocupado.set(false);}}
 async acompanhar(id:number){await this.router.navigate(['/pendencias'],{queryParams:{aba:'todas'}});this.ui.abrirPendencia(id);}
}
