import { Component,effect,inject,signal,untracked } from '@angular/core'; import { RouterLink } from '@angular/router'; import { CurrencyPipe,DatePipe } from '@angular/common';
import { API } from '../../core/api/api.service'; import { AuthService } from '../../core/auth/auth.service'; import { UiService } from '../../core/ui.service'; import { Dashboard as Dados,ItemFolha } from '../../core/models/modelos';
import { PageHeader } from '../../shared/components/page-header'; import { Icone } from '../../shared/components/icone'; import { Skeleton,EmptyState } from '../../shared/components/estados'; import { PendenciasTable } from '../../shared/components/pendencias-table'; import { FolhaStepper } from '../../shared/components/folha-stepper'; import { Avatar } from '../../shared/components/badges';
@Component({selector:'fc-dashboard',imports:[RouterLink,CurrencyPipe,DatePipe,PageHeader,Icone,Skeleton,EmptyState,PendenciasTable,FolhaStepper,Avatar],template:`
<fc-page-header [contexto]="auth.usuario()?.empresa?.nome || ''" [titulo]="'Olá, '+primeiroNome()+'.'" descricao="Veja o que precisa da sua atenção e mantenha a folha em dia.">@if(auth.setor()==='FUNCIONARIO'){<a class="button primary" routerLink="/solicitacoes/nova"><fc-icon nome="plus"/>Nova solicitação</a>}@else if(auth.setor()!=='ADMIN'){<a class="button primary" routerLink="/pendencias/nova"><fc-icon nome="plus"/>Nova pendência</a>}</fc-page-header>
@if(carregando()){<fc-skeleton/>}@else if(erro()){<div class="error-state" role="alert">{{erro()}}<button class="button" (click)="carregar()">Tentar de novo</button></div>}@else if(dados();as d){
@if(auth.setor()==='FUNCIONARIO'){<div class="employee-actions"><a class="card employee-action" routerLink="/solicitacoes/nova"><span class="action-icon"><fc-icon nome="upload" [tamanho]="24"/></span><h3>Enviar atestado</h3><p>Envie um documento ou faça uma solicitação ao RH.</p><span class="action-link">Enviar documento <fc-icon nome="arrow-right"/></span></a><a class="card employee-action" routerLink="/ponto"><span class="action-icon"><fc-icon nome="clock-3" [tamanho]="24"/></span><h3>Registrar ponto</h3><p>Acompanhe suas entradas, saídas e marcações do mês.</p><span class="action-link">Abrir meu ponto <fc-icon nome="arrow-right"/></span></a><a class="card employee-action" routerLink="/holerites"><span class="action-icon"><fc-icon nome="receipt" [tamanho]="24"/></span><h3>Meu último holerite</h3><strong class="last-money">{{holerite()?.liquido|currency:'BRL'}}</strong><p>{{holerite()?'Competência '+holerite()!.competencia:'Confira os holerites publicados.'}}</p><span class="action-link">Ver holerites <fc-icon nome="arrow-right"/></span></a></div>}
@else{<div class="kpi-grid"><a class="card kpi" routerLink="/pendencias" [queryParams]="{aba:'todas'}"><div><span>Pendências abertas</span><fc-icon nome="clipboard-list"/></div><strong>{{d.abertas}}</strong><small>Acompanhe cada próximo passo <fc-icon nome="arrow-up-right" [tamanho]="14"/></small></a><a class="card kpi" routerLink="/pendencias" [queryParams]="{aba:'semana'}"><div><span>Vencem em 3 dias</span><fc-icon nome="calendar-clock"/></div><strong>{{d.vencemEmTresDias}}</strong><small>Planeje as próximas ações <fc-icon nome="arrow-up-right" [tamanho]="14"/></small></a><a class="card kpi" [class.kpi-danger]="d.atrasadas>0" routerLink="/pendencias" [queryParams]="{aba:'atrasadas'}"><div><span>Pendências atrasadas</span><fc-icon nome="circle-alert"/></div><strong>{{d.atrasadas}}</strong><small>{{d.atrasadas?'Precisam de atenção agora':'Tudo dentro do prazo'}}<fc-icon nome="arrow-up-right" [tamanho]="14"/></small></a><a class="card kpi" routerLink="/pendencias" [queryParams]="{status:'EM_ANALISE',aba:'todas'}"><div><span>Aguardando validação</span><fc-icon nome="scan-search"/></div><strong>{{d.aguardandoValidacao}}</strong><small>Documentos e solicitações <fc-icon nome="arrow-up-right" [tamanho]="14"/></small></a></div>}
@if(d.atrasadas && auth.setor()!=='FUNCIONARIO'){<div class="action-banner"><span class="banner-icon"><fc-icon nome="circle-alert"/></span><div><strong>Tem {{d.atrasadas}} {{d.atrasadas===1?'pendência que precisa':'pendências que precisam'}} de atenção.</strong><p>Resolver os atrasos ajuda todos os setores a avançar.</p></div><a routerLink="/pendencias" [queryParams]="{aba:'atrasadas'}">Ver atrasadas<fc-icon nome="arrow-right" [tamanho]="16"/></a></div>}
<section class="card action-section"><div class="card-heading"><div><div class="heading-line"><span class="section-icon"><fc-icon nome="hand"/></span><h2>{{auth.setor()==='FUNCIONARIO'?'Suas solicitações em andamento':'Precisa da sua ação'}}</h2><span class="count-pill">{{d.precisaAcao.length}}</span></div><p>Os próximos prazos que estão com {{auth.setor()==='FUNCIONARIO'?'você':'o seu setor'}}.</p></div><a routerLink="/pendencias" [queryParams]="{aba:'comigo'}">Ver todas<fc-icon nome="arrow-right" [tamanho]="16"/></a></div><fc-pendencias-table [itens]="d.precisaAcao" (abrir)="ui.abrirPendencia($event)"/></section>
<div class="dashboard-bottom">@if(d.folha;as f){<section class="card closing-card"><div class="card-heading"><div><h2>Fechamento da folha</h2><p>{{mes()}} · {{auth.usuario()?.empresa?.nome}}</p></div><a routerLink="/folha"><fc-icon nome="arrow-up-right"/></a></div><fc-folha-stepper [folha]="f"/>@if(f.bloqueada){<div class="closing-notice"><fc-icon nome="lock-keyhole"/><div><strong>Bloqueada por {{f.bloqueios.length}} pendências</strong><p>Resolva as pendências bloqueantes para avançar.</p></div><a routerLink="/folha">Ver bloqueios</a></div>}@else{<div class="notice success"><fc-icon nome="circle-check"/>Sem pendências bloqueantes para esta competência.</div>}</section>}
<section class="card activity-card"><div class="card-heading"><div><h2>Últimas atividades</h2><p>As atualizações que conectam os setores.</p></div><fc-icon nome="activity"/></div><div class="activity-list">@for(evento of d.atividades;track evento.id){<div class="activity"><fc-avatar [nome]="evento.autor" [setor]="evento.papeis[0]" [pequeno]="true"/><div><strong>{{evento.autor}}</strong><p>{{evento.comentario}}</p><time>{{evento.criadoEm|date:'dd/MM · HH:mm'}}</time></div></div>}@empty{<fc-empty titulo="Tudo tranquilo por aqui" descricao="As próximas atualizações aparecerão aqui."/>}</div></section></div>
}`})
export class Dashboard {
 readonly auth=inject(AuthService);readonly ui=inject(UiService);private api=inject(API);readonly dados=signal<Dados|null>(null);readonly holerite=signal<ItemFolha|null>(null);readonly carregando=signal(true);readonly erro=signal('');
 constructor(){effect(()=>{this.ui.competencia();this.ui.versao();untracked(()=>void this.carregar());});}
 primeiroNome(){return this.auth.usuario()?.nome.split(' ')[0]||'';}
 mes(){return new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(this.ui.competencia()+'-15T12:00:00'));}
 async carregar(){this.carregando.set(true);this.erro.set('');try{const d=await this.api.get<Dados>('/dashboard',{competencia:this.ui.competencia()});this.dados.set(d);this.ui.hoje.set(d.hoje);if(this.auth.tem('FUNCIONARIO'))this.holerite.set((await this.api.get<ItemFolha[]>('/holerites/me'))[0]||null);}catch(e){this.erro.set(this.ui.mensagem(e));}finally{this.carregando.set(false);}}
}
