import { Component,inject,signal } from '@angular/core'; import { CurrencyPipe } from '@angular/common'; import { DrawerModule } from 'primeng/drawer';
import { API } from '../../core/api/api.service'; import { UiService } from '../../core/ui.service'; import { ItemFolha } from '../../core/models/modelos'; import { PageHeader } from '../../shared/components/page-header'; import { Icone } from '../../shared/components/icone'; import { Skeleton,EmptyState } from '../../shared/components/estados';
@Component({selector:'fc-holerites',imports:[CurrencyPipe,DrawerModule,PageHeader,Icone,Skeleton,EmptyState],template:`<fc-page-header titulo="Meus holerites" descricao="Seus demonstrativos, disponíveis depois da publicação pelo Financeiro."/>@if(carregando()){<fc-skeleton/>}@else if(erro()){<div class="error-state" role="alert">{{erro()}}<button class="button" (click)="carregar()">Tentar de novo</button></div>}@else if(!itens().length){<section class="card"><fc-empty titulo="Seu holerite ainda não foi publicado" descricao="Assim que o Financeiro publicar, ele aparecerá aqui."/></section>}@else{<div class="holerite-grid">@for(item of itens();track item.id){<button class="card holerite-card" (click)="abrir(item)"><div class="holerite-icon"><fc-icon nome="receipt" [tamanho]="28"/></div><span class="badge status-concluida">Publicado</span><h2>{{mes(item.competencia)}}</h2><span class="muted">Valor líquido</span><strong>{{item.liquido|currency:'BRL'}}</strong><span class="action-link">Abrir demonstrativo<fc-icon nome="arrow-right"/></span></button>}</div>}
<p-drawer [visible]="!!selecionado()" (onHide)="selecionado.set(null)" position="right" header="Meu holerite" [style]="{width:'640px',maxWidth:'100vw'}">@if(selecionado();as i){<div class="drawer-content"><span class="eyebrow">{{mes(i.competencia)}}</span><h2>{{i.funcionarioNome}}</h2><div class="payslip-net"><span>Valor líquido</span><strong>{{i.liquido|currency:'BRL'}}</strong></div><div class="payslip-columns"><div><h3>Proventos</h3><dl><dt>Salário base</dt><dd>{{i.salarioBase|currency:'BRL'}}</dd><dt>Horas extras</dt><dd>{{i.valorHorasExtras|currency:'BRL'}}</dd></dl></div><div><h3>Descontos</h3><dl><dt>Faltas</dt><dd>{{i.valorFaltas|currency:'BRL'}}</dd><dt>INSS</dt><dd>{{i.inss|currency:'BRL'}}</dd><dt>IRRF</dt><dd>{{i.irrf|currency:'BRL'}}</dd><dt>Vale-transporte</dt><dd>{{i.valeTransporte|currency:'BRL'}}</dd></dl></div></div><p class="notice neutral">Demonstrativo da demonstração, com dados fictícios e cálculo simplificado.</p><button class="button primary" (click)="baixar(i)"><fc-icon nome="download"/>Baixar PDF</button></div>}</p-drawer>`})
export class Holerites {
 private api=inject(API);private ui=inject(UiService);readonly itens=signal<ItemFolha[]>([]);readonly selecionado=signal<ItemFolha|null>(null);readonly carregando=signal(true);readonly erro=signal('');constructor(){void this.carregar();}
 mes(competencia:string){return new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(competencia+'-15T12:00:00'));}
 async carregar(){this.carregando.set(true);this.erro.set('');try{this.itens.set((await this.api.get<ItemFolha[]>('/holerites/me')).sort((a,b)=>b.competencia.localeCompare(a.competencia)));}catch(e){this.erro.set(this.ui.mensagem(e));}finally{this.carregando.set(false);}}
 async abrir(item:ItemFolha){try{this.selecionado.set(await this.api.get<ItemFolha>(`/holerites/me/${item.competencia}`));}catch(e){this.ui.falhar(e);}}
 async baixar(i:ItemFolha){try{await this.ui.baixar(await this.api.arquivo(`/holerites/me/${i.competencia}/pdf`),`holerite-${i.competencia}.pdf`);}catch(e){this.ui.falhar(e);}}
}
