import { Component,computed,effect,inject,signal,untracked } from '@angular/core'; import { Router,RouterLink,RouterLinkActive,RouterOutlet } from '@angular/router'; import { FormsModule } from '@angular/forms'; import { DrawerModule } from 'primeng/drawer';
import { AuthService } from '../core/auth/auth.service'; import { API } from '../core/api/api.service'; import { UiService } from '../core/ui.service'; import { Papel,Notificacao,setores } from '../core/models/modelos';
import { Icone } from '../shared/components/icone'; import { Avatar,SetorBadge } from '../shared/components/badges'; import { PendenciaDrawer } from '../shared/components/pendencia-drawer'; import { environment } from '../../environments/environment'; import { TempoRelativoPipe } from '../shared/pipes/tempo-relativo.pipe';
@Component({selector:'fc-shell',imports:[RouterLink,RouterLinkActive,RouterOutlet,FormsModule,DrawerModule,Icone,Avatar,SetorBadge,PendenciaDrawer,TempoRelativoPipe],template:`
<div class="app-shell">@if(menuAberto()){<button class="mobile-shade" aria-label="Fechar menu" (click)="menuAberto.set(false)"></button>}
<aside class="sidebar" [class.aberta]="menuAberto()"><a class="logo" routerLink="/inicio"><span class="logo-mark"><fc-icon nome="workflow" [tamanho]="24"/></span><span>Folha<span class="logo-light">Conecta</span></span></a><div class="sidebar-company"><fc-icon nome="building-2"/><div><small>EMPRESA ATIVA</small><strong>{{auth.usuario()?.empresa?.nome}}</strong></div></div><span class="nav-label">ÁREA DE TRABALHO</span><nav aria-label="Menu principal">@for(item of menu();track item.rota){<a [routerLink]="item.rota" routerLinkActive="ativa" (click)="menuAberto.set(false)"><fc-icon [nome]="item.icone"/><span>{{item.nome}}</span>@if(item.rota==='/pendencias'){<span class="nav-counter">{{abertas()}}</span>}</a>}</nav>
@if(demo){<div class="sidebar-demo"><span class="demo-dot"></span><strong>Ambiente de demonstração</strong><small>Dados fictícios · Outubro de 2026</small>@if(auth.tem('RH','ADMIN')){<button (click)="resetar()" [disabled]="resetando()"><fc-icon nome="rotate-ccw" [tamanho]="14"/>{{resetando()?'Restaurando…':'Resetar demo'}}</button>}</div>}
<div class="sidebar-user"><fc-avatar [nome]="auth.usuario()?.nome || ''" [setor]="auth.setor()!"/><div><strong>{{auth.usuario()?.nome}}</strong><fc-setor [valor]="auth.setor()!"/></div><button class="icon-button" aria-label="Sair da conta" title="Sair" (click)="auth.sair()"><fc-icon nome="log-out"/></button></div></aside>
<div class="app-main"><header class="topbar"><button class="icon-button mobile-menu" aria-label="Abrir menu" (click)="menuAberto.set(true)"><fc-icon nome="menu"/></button><form class="global-search" (ngSubmit)="buscar()"><fc-icon nome="search"/><input name="busca" [(ngModel)]="busca" placeholder="Buscar funcionário ou pendência…" aria-label="Busca global"/><kbd>↵</kbd></form><div class="topbar-right">@if(auth.tem('CONTABILIDADE') && auth.usuario()!.empresas.length>1){<select class="company-select" aria-label="Empresa ativa" [ngModel]="auth.usuario()!.empresa.id" (ngModelChange)="trocarEmpresa($event)">@for(empresa of auth.usuario()!.empresas;track empresa.id){<option [ngValue]="empresa.id">{{empresa.nome}}</option>}</select>}<label class="competencia"><fc-icon nome="calendar-days"/><select aria-label="Competência" [ngModel]="ui.competencia()" (ngModelChange)="ui.competencia.set($event)"><option value="2026-10">Outubro / 2026</option><option value="2026-09">Setembro / 2026</option><option value="2026-08">Agosto / 2026</option></select></label><button class="icon-button bell" aria-label="Abrir notificações" (click)="notificacoesAbertas.set(true)"><fc-icon nome="bell"/>@if(naoLidas()){<span>{{naoLidas()}}</span>}</button><div class="user-dropdown"><button class="topbar-user" aria-label="Menu do usuário" (click)="usuarioAberto.set(!usuarioAberto())"><fc-avatar [nome]="auth.usuario()?.nome || ''" [setor]="auth.setor()!" [pequeno]="true"/><fc-icon nome="chevron-down" [tamanho]="14"/></button>@if(usuarioAberto()){<div class="dropdown"><strong>{{auth.usuario()?.nome}}</strong><small>{{setores[auth.setor()!]}}</small>@if(auth.usuario()!.papeis.length>1){<a routerLink="/escolher-setor" (click)="usuarioAberto.set(false)">Trocar setor</a>}<button (click)="auth.sair()">Sair da conta</button></div>}</div></div></header>
<main class="page-content"><router-outlet/></main><footer class="app-footer"><span>Folha Conecta · Pessoas e folha, conectadas.</span><span>{{demo?'Demonstração · Dados fictícios':'Acesso seguro por setor'}}</span></footer></div>
</div>
<fc-pendencia-drawer [id]="ui.pendenciaId()" (fechar)="ui.pendenciaId.set(null)" (mudou)="ui.atualizar()"/>
<p-drawer [visible]="notificacoesAbertas()" (onHide)="notificacoesAbertas.set(false)" position="right" header="Notificações" [style]="{width:'420px',maxWidth:'100vw'}">@if(!notificacoes().length){<div class="empty-state"><fc-icon nome="bell" [tamanho]="32"/><h3>Nenhuma notificação</h3><p>As atualizações das suas pendências aparecerão aqui.</p></div>}@for(n of notificacoes();track n.id){<button class="notification-row" [class.nova]="!n.lida" (click)="abrirNotificacao(n)"><fc-icon nome="message-square"/><div><strong>{{n.titulo}}</strong><p>{{n.mensagem}}</p><small>{{n.criadoEm|tempoRelativo}}</small></div></button>}</p-drawer>
@if(ui.toast()){<div class="toast" role="status"><fc-icon nome="circle-check"/>{{ui.toast()}}<button aria-label="Fechar aviso" (click)="ui.toast.set('')"><fc-icon nome="x" [tamanho]="16"/></button></div>}
@if(ui.erro()){<div class="toast error-toast" role="alert"><fc-icon nome="circle-alert"/>{{ui.erro()}}<button aria-label="Fechar erro" (click)="ui.erro.set('')"><fc-icon nome="x" [tamanho]="16"/></button></div>}`})
export class AppShell {
 readonly auth=inject(AuthService);readonly ui=inject(UiService);private api=inject(API);private router=inject(Router);readonly setores=setores;readonly demo=environment.demo;
 readonly menuAberto=signal(false);readonly usuarioAberto=signal(false);readonly notificacoesAbertas=signal(false);readonly notificacoes=signal<Notificacao[]>([]);readonly abertas=signal(0);readonly resetando=signal(false);busca='';
 readonly naoLidas=computed(()=>this.notificacoes().filter(n=>!n.lida).length);
 readonly menu=computed(()=>{const setor=this.auth.setor();return [
  {rota:'/inicio',nome:'Visão geral',icone:'layout-dashboard',papeis:['FUNCIONARIO','RH','FINANCEIRO','CONTABILIDADE','ADMIN']},
  {rota:'/pendencias',nome:'Central de Pendências',icone:'clipboard-list',papeis:['FUNCIONARIO','RH','FINANCEIRO','CONTABILIDADE','ADMIN']},
  {rota:'/ponto',nome:setor==='FUNCIONARIO'?'Meu ponto':'Ponto da equipe',icone:'clock-3',papeis:['FUNCIONARIO','RH']},
  {rota:'/funcionarios',nome:'Funcionários',icone:'users',papeis:['RH','ADMIN']},
  {rota:'/documentos',nome:'Validar documentos',icone:'files',papeis:['RH']},
  {rota:'/folha',nome:'Folha de pagamento',icone:'wallet',papeis:['RH','FINANCEIRO','CONTABILIDADE','ADMIN']},
  {rota:'/holerites',nome:'Meus holerites',icone:'file-text',papeis:['FUNCIONARIO']},
  {rota:'/meus-dados',nome:'Meus dados',icone:'user-round',papeis:['FUNCIONARIO']},
  {rota:'/empresas',nome:'Carteira de empresas',icone:'building-2',papeis:['CONTABILIDADE']},
  {rota:'/admin/usuarios',nome:'Usuários e setores',icone:'user-round-cog',papeis:['ADMIN']},
  {rota:'/admin/empresa',nome:'Dados da empresa',icone:'settings',papeis:['ADMIN']},
 ].filter(i=>i.papeis.includes(setor!));});
 constructor(){effect(()=>{this.ui.versao();this.auth.usuario();this.ui.competencia();untracked(()=>void this.carregar());});}
 async carregar(){try{const [n,p]=await Promise.all([this.api.get<Notificacao[]>('/notificacoes'),this.api.get<{totalElements:number}>('/pendencias',{competencia:this.ui.competencia(),size:1})]);this.notificacoes.set(n);this.abertas.set(p.totalElements);}catch(e){this.ui.falhar(e);}}
 buscar(){void this.router.navigate(['/pendencias'],{queryParams:{q:this.busca}});}
 async trocarEmpresa(id:number){try{await this.auth.trocarEmpresa(id);this.ui.pendenciaId.set(null);this.ui.atualizar();this.ui.avisar('Empresa ativa atualizada.');}catch(e){this.ui.falhar(e);}}
 async abrirNotificacao(n:Notificacao){try{await this.api.patch(`/notificacoes/${n.id}/lida`,{});this.notificacoesAbertas.set(false);const id=new URL(n.link,location.origin).searchParams.get('pendencia');if(id)this.ui.abrirPendencia(Number(id));else await this.router.navigateByUrl(n.link);await this.carregar();}catch(e){this.ui.falhar(e);}}
 async resetar(){this.resetando.set(true);try{await this.api.post('/demo/reset');this.ui.pendenciaId.set(null);this.ui.atualizar();this.ui.avisar('Demonstração restaurada.');}catch(e){this.ui.falhar(e);}finally{this.resetando.set(false);}}
}
