import { Component,inject,signal } from '@angular/core'; import { FormsModule } from '@angular/forms'; import { DialogModule } from 'primeng/dialog';
import { API } from '../../core/api/api.service'; import { UiService } from '../../core/ui.service'; import { Papel,UsuarioAdmin,setores } from '../../core/models/modelos'; import { PageHeader } from '../../shared/components/page-header'; import { Icone } from '../../shared/components/icone'; import { Avatar,SetorBadge } from '../../shared/components/badges'; import { Skeleton } from '../../shared/components/estados';
@Component({selector:'fc-usuarios',imports:[FormsModule,DialogModule,PageHeader,Icone,Avatar,SetorBadge,Skeleton],template:`<fc-page-header titulo="Usuários e setores" descricao="Defina quem tem acesso à empresa e o setor de cada conta."><button class="button primary" (click)="novo()"><fc-icon nome="user-round-plus"/>Novo usuário</button></fc-page-header><section class="card">@if(carregando()){<fc-skeleton/>}@else if(erro()){<div class="error-state">{{erro()}}<button class="button" (click)="carregar()">Tentar de novo</button></div>}@else{<div class="table-scroll"><table class="data-table"><thead><tr><th>Usuário</th><th>Login</th><th>Setores</th><th>Situação</th><th>Ação</th></tr></thead><tbody>@for(u of usuarios();track u.id){<tr><td><div class="person"><fc-avatar [nome]="u.nome" [setor]="u.papeis[0]" [pequeno]="true"/><strong>{{u.nome}}</strong></div></td><td>{{u.email||u.cpf}}</td><td><div class="row-actions">@for(p of u.papeis;track p){<fc-setor [valor]="p"/>}</div></td><td><span class="badge" [class.status-concluida]="u.ativo" [class.status-cancelada]="!u.ativo">{{u.ativo?'Ativo':'Inativo'}}</span></td><td><div class="row-actions"><button class="button small" (click)="editar(u)">Editar</button><button class="text-button" (click)="redefinir(u)">Redefinir acesso</button></div></td></tr>}</tbody></table></div>}</section>@if(convite()){<section class="card invite-card"><h3>Link de redefinição gerado</h3><label>Convite válido por 48 horas<input readonly [value]="convite()"/></label><button class="button" (click)="copiar()"><fc-icon nome="copy"/>Copiar link</button></section>}
<p-dialog [header]="editando()?'Editar usuário':'Novo usuário da empresa'" [visible]="aberto()" (visibleChange)="aberto.set($event)" [modal]="true" [style]="{width:'500px',maxWidth:'96vw'}"><form (ngSubmit)="salvar()"><label>Nome<input name="nome" [(ngModel)]="nome" required/></label>@if(!funcionario){<label>E-mail corporativo<input type="email" name="email" [(ngModel)]="email" required/></label>}<fieldset><legend>Setores autorizados</legend>@for(p of papeis;track p){<label class="checkbox"><input type="checkbox" [name]="p" [checked]="selecionados.includes(p)" [disabled]="funcionario" (change)="alternar(p)"/>{{setores[p]}}</label>}</fieldset><label class="checkbox"><input type="checkbox" name="ativo" [(ngModel)]="ativo"/>Conta ativa</label><label>{{editando()?'Nova senha (opcional)':'Senha inicial'}}<input type="password" name="senha" [(ngModel)]="senha" [required]="!editando()" minlength="8" maxlength="72" autocomplete="new-password"/></label>@if(erroForm()){<p class="inline-error" role="alert">{{erroForm()}}</p>}<button class="button primary" [disabled]="ocupado()">{{ocupado()?'Salvando…':'Salvar usuário'}}</button></form></p-dialog>`})
export class Usuarios {
 private api=inject(API);private ui=inject(UiService);readonly usuarios=signal<UsuarioAdmin[]>([]);readonly carregando=signal(true);readonly erro=signal('');readonly erroForm=signal('');readonly aberto=signal(false);readonly editando=signal<number|null>(null);readonly ocupado=signal(false);readonly convite=signal('');readonly setores=setores;readonly papeis:Papel[]=['RH','FINANCEIRO','CONTABILIDADE','ADMIN'];nome='';email='';senha='';ativo=true;selecionados:Papel[]=['RH'];funcionario=false;constructor(){void this.carregar();}
 async carregar(){this.carregando.set(true);this.erro.set('');try{this.usuarios.set(await this.api.get<UsuarioAdmin[]>('/admin/usuarios'));}catch(e){this.erro.set(this.ui.mensagem(e));}finally{this.carregando.set(false);}}
 novo(){this.editando.set(null);this.nome=this.email=this.senha='';this.ativo=true;this.selecionados=['RH'];this.funcionario=false;this.erroForm.set('');this.aberto.set(true);}
 editar(u:UsuarioAdmin){this.editando.set(u.id);this.nome=u.nome;this.email=u.email||'';this.senha='';this.ativo=u.ativo;this.selecionados=[...u.papeis];this.funcionario=u.papeis.includes('FUNCIONARIO');this.erroForm.set('');this.aberto.set(true);}
 alternar(p:Papel){this.selecionados=this.selecionados.includes(p)?this.selecionados.filter(v=>v!==p):[...this.selecionados,p];}
 async salvar(){this.ocupado.set(true);this.erroForm.set('');try{const dados={nome:this.nome,email:this.email||null,papeis:this.selecionados,ativo:this.ativo,senha:this.senha||null};if(this.editando())await this.api.put(`/admin/usuarios/${this.editando()}`,dados);else await this.api.post('/admin/usuarios',dados);this.aberto.set(false);await this.carregar();this.ui.avisar('Usuário atualizado.');}catch(e){this.erroForm.set(this.ui.mensagem(e));}finally{this.ocupado.set(false);}}
 async redefinir(u:UsuarioAdmin){try{const p=await this.api.post<{convite:string}>(`/usuarios/${u.id}/redefinir-senha`);this.convite.set(location.origin+p.convite);}catch(e){this.ui.falhar(e);}}
 async copiar(){try{await navigator.clipboard.writeText(this.convite());this.ui.avisar('Link copiado.');}catch{this.ui.avisar('Selecione o link para copiar.');}}
}
