package br.com.folhaconecta.folha;
import br.com.folhaconecta.folha.dto.*; import br.com.folhaconecta.pendencia.*; import br.com.folhaconecta.pendencia.dto.*;
import br.com.folhaconecta.funcionario.*; import br.com.folhaconecta.ponto.*; import br.com.folhaconecta.auth.*; import br.com.folhaconecta.usuario.*; import br.com.folhaconecta.shared.exception.*;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.util.*; import lombok.RequiredArgsConstructor;
@Service @RequiredArgsConstructor
public class FolhaService {
 private final FolhaRepository folhas; private final ItemFolhaRepository itens; private final FuncionarioRepository funcionarios;
 private final PendenciaRepository pendencias; private final PendenciaService servicoPendencia; private final PontoService ponto;
 private final CalculoFolhaService calculo; private final TabelasFiscais tabelas; private final UsuarioLogado logado;
 private List<Pendencia> bloqueantes(String competencia){return pendencias.findByEmpresaId(logado.empresaId()).stream().filter(p->competencia.equals(p.getCompetencia())&&p.isBloqueiaFolha()&&p.getStatus()!=StatusPendencia.CONCLUIDA&&p.getStatus()!=StatusPendencia.CANCELADA).toList();}
 private Folha buscar(String competencia){YearMonth.parse(competencia);return folhas.findByEmpresaIdAndCompetencia(logado.empresaId(),competencia).orElseThrow(NaoEncontradoException::new);}
 private Folha bloquear(String competencia){YearMonth.parse(competencia);return folhas.bloquear(logado.empresaId(),competencia).orElseGet(()->{var folha=new Folha();folha.setEmpresa(logado.empresa());folha.setCompetencia(competencia);folha.setStatus(StatusFolha.ABERTA);return folhas.save(folha);});}
 @Transactional(readOnly=true) public FolhaResponse detalhe(String competencia){YearMonth.parse(competencia);var folha=folhas.findByEmpresaIdAndCompetencia(logado.empresaId(),competencia).orElse(null);return resumir(folha,competencia);}
 private FolhaResponse resumir(Folha folha,String competencia){var bloqueios=bloqueantes(competencia).stream().map(servicoPendencia::resumir).toList();var status=folha==null?StatusFolha.ABERTA:folha.getStatus();return new FolhaResponse(folha==null?null:folha.getId(),competencia,status,folha==null?null:folha.getCalculadaEm(),folha==null?null:folha.getFechadaEm(),!bloqueios.isEmpty(),bloqueios,List.of("Ponto","Documentos","Previa","Conferencia","Fechada"),status==StatusFolha.FECHADA?4:status==StatusFolha.EM_CONFERENCIA?3:status==StatusFolha.PREVIA_CALCULADA?2:0);}
 @Transactional public FolhaResponse calcular(String competencia){
  logado.exigir(Papel.FINANCEIRO);var folha=bloquear(competencia);if(folha.getStatus()==StatusFolha.FECHADA)throw new RegraNegocioException("Folha fechada nao pode ser recalculada.");if(folha.getStatus()==StatusFolha.EM_CONFERENCIA)throw new RegraNegocioException("Folha ja enviada para conferencia.");
  var mes=YearMonth.parse(competencia);if(mes.getYear()!=tabelas.ano())throw new RegraNegocioException("Configure a tabela fiscal do ano antes de calcular.");
  var existentes=itens.findByFolhaIdAndEmpresaId(folha.getId(),logado.empresaId());var abonos=pendencias.findByEmpresaId(logado.empresaId()).stream().filter(p->p.isAbonado()&&p.getStatus()!=StatusPendencia.CANCELADA&&p.getDataInicio()!=null&&p.getDataFim()!=null).toList();
  for(var funcionario:funcionarios.findByEmpresaId(logado.empresaId()))if(funcionario.isAtivo()){
   var abonados=new HashSet<LocalDate>();for(var abono:abonos)if(abono.getFuncionario().getId().equals(funcionario.getId()))for(var dia=abono.getDataInicio().isBefore(mes.atDay(1))?mes.atDay(1):abono.getDataInicio();!dia.isAfter(abono.getDataFim())&&!dia.isAfter(mes.atEndOfMonth());dia=dia.plusDays(1))abonados.add(dia);
   var item=calculo.calcular(funcionario,ponto.resumo(funcionario,competencia),abonados);item.setFolha(folha);var anterior=existentes.stream().filter(i->i.getFuncionario().getId().equals(funcionario.getId())).findFirst();anterior.ifPresent(i->{item.setId(i.getId());item.setCriadoEm(i.getCriadoEm());});itens.save(item);
  }folha.setStatus(StatusFolha.PREVIA_CALCULADA);folha.setCalculadaEm(LocalDateTime.now());return resumir(folha,competencia);
 }
 @Transactional(readOnly=true) public List<ItemFolhaResponse> listarItens(String competencia){var folha=buscar(competencia);var bloqueios=bloqueantes(competencia);return itens.findByFolhaIdAndEmpresaId(folha.getId(),logado.empresaId()).stream().map(i->ItemFolhaResponse.de(i,bloqueios.stream().filter(p->p.getFuncionario().getId().equals(i.getFuncionario().getId())).map(p->"Bloqueado: "+p.getTitulo()).findFirst().orElse("OK"))).toList();}
 @Transactional(readOnly=true) public ItemFolhaResponse memoria(String competencia,Long id){var item=itens.findByIdAndEmpresaId(id,logado.empresaId()).orElseThrow(NaoEncontradoException::new);if(!item.getFolha().getCompetencia().equals(competencia))throw new NaoEncontradoException();return ItemFolhaResponse.de(item,"OK");}
 private void semBloqueios(String competencia){var lista=bloqueantes(competencia);if(!lista.isEmpty())throw new RegraNegocioException("Folha bloqueada por "+lista.size()+" pendencias. Resolva os bloqueios para continuar.",lista.stream().map(servicoPendencia::resumir).toList());}
 @Transactional public FolhaResponse enviar(String competencia){logado.exigir(Papel.FINANCEIRO);var folha=bloquear(competencia);semBloqueios(competencia);if(folha.getStatus()!=StatusFolha.PREVIA_CALCULADA)throw new RegraNegocioException("Calcule a previa antes de enviar.");folha.setStatus(StatusFolha.EM_CONFERENCIA);return resumir(folha,competencia);}
 @Transactional public FolhaResponse fechar(String competencia){logado.exigir(Papel.CONTABILIDADE);var folha=bloquear(competencia);semBloqueios(competencia);if(folha.getStatus()!=StatusFolha.EM_CONFERENCIA)throw new RegraNegocioException("A folha precisa estar em conferencia.");folha.setStatus(StatusFolha.FECHADA);folha.setFechadaEm(LocalDateTime.now());folha.setFechadaPor(logado.usuario());return resumir(folha,competencia);}
 @Transactional public FolhaResponse publicar(String competencia){logado.exigir(Papel.FINANCEIRO);var folha=bloquear(competencia);if(folha.getStatus()!=StatusFolha.FECHADA)throw new RegraNegocioException("A Contabilidade precisa fechar a folha antes da publicacao.");itens.findByFolhaIdAndEmpresaId(folha.getId(),logado.empresaId()).forEach(i->i.setPublicado(true));return resumir(folha,competencia);}
 @Transactional(readOnly=true) public List<ItemFolhaResponse> meusHolerites(){logado.exigir(Papel.FUNCIONARIO);return itens.findByFuncionarioIdAndEmpresaIdAndPublicadoTrueOrderByCriadoEmDesc(logado.funcionarioId(),logado.empresaId()).stream().map(i->ItemFolhaResponse.de(i,"Publicado")).toList();}
 @Transactional(readOnly=true) public ItemFolhaResponse meuHolerite(String competencia){return meusHolerites().stream().filter(i->i.competencia().equals(competencia)).findFirst().orElseThrow(NaoEncontradoException::new);}
}
