import { Component,inject,signal } from '@angular/core'; import { FormsModule } from '@angular/forms'; import { ActivatedRoute,RouterLink,Router } from '@angular/router';
import { API } from '../../core/api/api.service'; import { AuthService } from '../../core/auth/auth.service'; import { UiService } from '../../core/ui.service'; import { Papel,setores } from '../../core/models/modelos';
@Component({selector:'fc-acesso',imports:[FormsModule,RouterLink],template:`<main class="access-page"><div class="card access-card"><a routerLink="/login" class="eyebrow">FOLHA CONECTA</a><h1>{{titulo}}</h1>@if(modo==='setor'){<p class="muted">Sua conta tem mais de um setor. Escolha sua área de trabalho.</p>@for(papel of auth.usuario()?.papeis;track papel){<button class="button access-option" (click)="escolher(papel)">{{setores[papel]}}</button>}}@else{<p class="muted">{{modo==='primeiro'?'Use o convite recebido do RH para criar sua senha.':'Informe seu CPF ou e-mail. O responsável receberá o pedido de recuperação.'}}</p><form (ngSubmit)="enviar()">@if(modo==='primeiro'){<label>Token do convite<input name="token" [(ngModel)]="token" required/></label><label>Nova senha<input name="senha" type="password" [(ngModel)]="senha" minlength="8" maxlength="72" required autocomplete="new-password"/></label><label>Confirme a senha<input name="confirmacao" type="password" [(ngModel)]="confirmacao" minlength="8" required autocomplete="new-password"/></label>}@else{<label>CPF ou e-mail<input name="login" [(ngModel)]="login" required/></label>}@if(erro()){<p class="inline-error" role="alert">{{erro()}}</p>}@if(sucesso()){<p class="notice success" role="status">{{sucesso()}}</p>}<button class="button primary" [disabled]="ocupado()">{{ocupado()?'Enviando…':modo==='primeiro'?'Criar senha':'Solicitar recuperação'}}</button></form><a routerLink="/login" class="back-link">Voltar ao login</a>}</div></main>`})
export class Acesso {
 private route=inject(ActivatedRoute); private router=inject(Router); private api=inject(API); readonly auth=inject(AuthService);private ui=inject(UiService);
 readonly modo=this.route.snapshot.data['modo'] as string;readonly titulo=this.modo==='primeiro'?'Seu primeiro acesso':this.modo==='setor'?'Em qual setor vamos trabalhar?':'Recuperar acesso';readonly setores=setores;
 token=this.route.snapshot.queryParamMap.get('token')||'';senha='';confirmacao='';login='';readonly ocupado=signal(false);readonly erro=signal('');readonly sucesso=signal('');
 async escolher(papel:Papel){this.auth.setor.set(papel);await this.router.navigateByUrl('/inicio');}
 async enviar(){if(this.modo==='primeiro'&&this.senha!==this.confirmacao){this.erro.set('As senhas precisam ser iguais.');return;}this.ocupado.set(true);this.erro.set('');try{const resultado=await this.api.post<{mensagem:string}>(this.modo==='primeiro'?'/auth/primeiro-acesso':'/auth/esqueci-senha',this.modo==='primeiro'?{token:this.token,senha:this.senha}:{login:this.login});this.sucesso.set(resultado.mensagem);}catch(e){this.erro.set(this.ui.mensagem(e));}finally{this.ocupado.set(false);}}
}
