import { Component,inject,signal } from '@angular/core'; import { FormsModule } from '@angular/forms'; import { RouterLink,ActivatedRoute } from '@angular/router'; import { NgxMaskDirective } from 'ngx-mask';
import { AuthService } from '../../core/auth/auth.service'; import { UiService } from '../../core/ui.service'; import { Icone } from '../../shared/components/icone'; import { environment } from '../../../environments/environment'; import { Papel } from '../../core/models/modelos';
@Component({selector:'fc-login',imports:[FormsModule,RouterLink,Icone,NgxMaskDirective],template:`
<div class="login-page"><aside class="login-brand"><a class="logo" routerLink="/login"><span class="logo-mark"><fc-icon nome="workflow" [tamanho]="26"/></span><span>Folha<span class="logo-light">Conecta</span></span></a><div class="login-message"><span class="login-eyebrow">PESSOAS, PRAZOS E FOLHA. CONECTADOS.</span><h1>Todas as pendências<br/>da folha em um<br/><em>só lugar.</em></h1><p>O que aconteceu. Quem precisa resolver.<br/>Qual é o próximo passo.</p><div class="login-flow"><span>Funcionário</span><fc-icon nome="arrow-right"/><span>RH</span><fc-icon nome="arrow-right"/><span>Contabilidade</span></div></div><small>Mais clareza para quem cuida de pessoas.</small></aside>
<main class="login-form-area"><div class="login-card"><span class="eyebrow">BEM-VINDO À FOLHA CONECTA</span><h2>Vamos colocar tudo em dia?</h2><p class="muted">Entre para acompanhar suas pendências e próximos passos.</p><div class="login-tabs" role="tablist" aria-label="Tipo de acesso"><button role="tab" [attr.aria-selected]="tipo==='FUNCIONARIO'" [class.ativo]="tipo==='FUNCIONARIO'" (click)="alternar('FUNCIONARIO')"><fc-icon nome="user-round"/>Sou funcionário</button><button role="tab" [attr.aria-selected]="tipo==='EMPRESA'" [class.ativo]="tipo==='EMPRESA'" (click)="alternar('EMPRESA')"><fc-icon nome="building-2"/>Sou empresa</button></div>
<form (ngSubmit)="entrar()"><label>{{tipo==='FUNCIONARIO'?'CPF':'E-mail corporativo'}}@if(tipo==='FUNCIONARIO'){<input name="login" [(ngModel)]="login" mask="000.000.000-00" inputmode="numeric" autocomplete="username" placeholder="000.000.000-00" required/>}@else{<input name="login" [(ngModel)]="login" type="email" autocomplete="username" placeholder="voce@empresa.com.br" required/>}</label><label>Senha<input name="senha" [(ngModel)]="senha" type="password" autocomplete="current-password" placeholder="Digite sua senha" minlength="8" required/></label><a routerLink="/recuperar-senha" class="forgot">Esqueci minha senha</a>@if(erro()){<div class="inline-error" role="alert">{{erro()}}</div>}@if(expirada){<div class="notice warning">Sua sessão expirou. Entre novamente para continuar.</div>}<button class="button primary login-submit" [disabled]="ocupado()" type="submit">{{ocupado()?'Entrando…':'Entrar na minha conta'}}<fc-icon nome="arrow-right"/></button></form><p class="first-access">Recebeu um convite? <a routerLink="/primeiro-acesso">Primeiro acesso</a></p>
@if(demo){<div class="demo-login"><span class="eyebrow">EXPLORE A DEMONSTRAÇÃO</span><p>Dados fictícios. Entre com um perfil:</p><div>@for(perfil of demos;track perfil.papel){<button class="button" [disabled]="ocupado()" (click)="entrarDemo(perfil.papel)">{{perfil.nome}}</button>}</div><small>Senha demo: Demo&#64;2026 · CPF: 000.000.000-01</small></div>}
</div><small class="login-footer"><fc-icon nome="shield-check" [tamanho]="14"/>Seus dados, com acesso para quem precisa.</small></main></div>`})
export class Login {
 readonly auth=inject(AuthService); private ui=inject(UiService); private route=inject(ActivatedRoute); readonly demo=environment.demo;
 readonly ocupado=signal(false); readonly erro=signal(''); readonly expirada=!!this.route.snapshot.queryParamMap.get('expirada');tipo:'FUNCIONARIO'|'EMPRESA'='FUNCIONARIO';login='';senha='';
 readonly demos=[{papel:'FUNCIONARIO' as Papel,nome:'Funcionário'},{papel:'RH' as Papel,nome:'RH'},{papel:'FINANCEIRO' as Papel,nome:'Financeiro'},{papel:'CONTABILIDADE' as Papel,nome:'Contabilidade'},{papel:'ADMIN' as Papel,nome:'Admin'}];
 alternar(tipo:'FUNCIONARIO'|'EMPRESA'){this.tipo=tipo;this.login='';this.erro.set('');}
 async entrar(){this.ocupado.set(true);this.erro.set('');try{await this.auth.entrar(this.tipo,this.login,this.senha);}catch(e){this.erro.set(this.ui.mensagem(e));}finally{this.ocupado.set(false);}}
 async entrarDemo(papel:Papel){this.tipo=papel==='FUNCIONARIO'?'FUNCIONARIO':'EMPRESA';this.login=papel==='FUNCIONARIO'?'00000000001':{RH:'rh@demo.com',FINANCEIRO:'financeiro@demo.com',CONTABILIDADE:'contabil@demo.com',ADMIN:'admin@demo.com'}[papel];this.senha='Demo@2026';await this.entrar();}
}
