import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
await fs.mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const erros=[];page.on('pageerror',e=>erros.push(e.message));
await page.goto('http://127.0.0.1:5173/');
await page.getByRole('button',{name:'RH',exact:true}).waitFor();
await page.screenshot({path:'artifacts/login.png',fullPage:true});
await page.getByRole('button',{name:'RH',exact:true}).click();
await page.getByRole('heading',{name:'Olá, Valdir.'}).waitFor();
await page.getByText('Carregando',{exact:true}).count();
await page.waitForTimeout(1200);
await page.screenshot({path:'artifacts/dashboard-rh.png',fullPage:true});
await page.getByRole('link',{name:'Central de Pendências'}).click();
await page.getByRole('tab',{name:/Todas/}).click();
await page.locator('.data-table tbody tr').first().waitFor();
await page.screenshot({path:'artifacts/central.png',fullPage:true});
await page.locator('.row-link').first().click();
await page.getByText('Histórico da pendência',{exact:true}).waitFor();
await page.screenshot({path:'artifacts/drawer.png',fullPage:true});
console.log(JSON.stringify({erros,linhas:await page.locator('.data-table tbody tr').count()}));
await browser.close();
