package br.com.folhaconecta.pendencia;
import br.com.folhaconecta.pendencia.dto.MudarStatusRequest; import br.com.folhaconecta.usuario.*; import br.com.folhaconecta.shared.exception.RegraNegocioException;
import org.junit.jupiter.api.Test; import java.util.Set; import static org.junit.jupiter.api.Assertions.*;
class TransicaoStatusTest {
 private Pendencia pendencia(StatusPendencia status,Papel setor){var p=new Pendencia();p.setStatus(status);p.setSetorResponsavel(setor);var u=new Usuario();u.setId(1L);p.setCriadoPor(u);return p;}
 private void validar(Pendencia p,StatusPendencia status,Papel destino,Papel autor,String comentario){TransicaoStatus.validar(p,new MudarStatusRequest(status,destino,comentario),Set.of(autor),2L);}
 @Test void somenteResponsavelInicia(){var p=pendencia(StatusPendencia.ABERTA,Papel.RH);assertDoesNotThrow(()->validar(p,StatusPendencia.EM_ANALISE,Papel.RH,Papel.RH,""));assertThrows(RegraNegocioException.class,()->validar(p,StatusPendencia.EM_ANALISE,Papel.RH,Papel.FINANCEIRO,""));}
 @Test void iniciarNaoMudaSetor(){assertThrows(RegraNegocioException.class,()->validar(pendencia(StatusPendencia.ABERTA,Papel.RH),StatusPendencia.EM_ANALISE,Papel.CONTABILIDADE,Papel.RH,""));}
 @Test void rhPodeAprovarEEncaminhar(){var p=pendencia(StatusPendencia.EM_ANALISE,Papel.RH);assertDoesNotThrow(()->validar(p,StatusPendencia.EM_ANALISE,Papel.CONTABILIDADE,Papel.RH,"Aprovado"));assertDoesNotThrow(()->validar(p,StatusPendencia.EM_ANALISE,Papel.FINANCEIRO,Papel.RH,"Aprovado"));}
 @Test void outroSetorNaoAprovaAtestado(){assertThrows(RegraNegocioException.class,()->validar(pendencia(StatusPendencia.EM_ANALISE,Papel.CONTABILIDADE),StatusPendencia.EM_ANALISE,Papel.FINANCEIRO,Papel.CONTABILIDADE,"Aprovado"));}
 @Test void correcaoExigeMotivoEDestinoCorreto(){var p=pendencia(StatusPendencia.EM_ANALISE,Papel.RH);assertThrows(RegraNegocioException.class,()->validar(p,StatusPendencia.CORRECAO_SOLICITADA,Papel.FUNCIONARIO,Papel.RH," "));assertDoesNotThrow(()->validar(p,StatusPendencia.CORRECAO_SOLICITADA,Papel.FUNCIONARIO,Papel.RH,"Data ilegivel"));assertThrows(RegraNegocioException.class,()->validar(p,StatusPendencia.CORRECAO_SOLICITADA,Papel.RH,Papel.RH,"Data ilegivel"));}
 @Test void contabilidadePedeCorrecaoAoRh(){var p=pendencia(StatusPendencia.EM_ANALISE,Papel.CONTABILIDADE);assertDoesNotThrow(()->validar(p,StatusPendencia.CORRECAO_SOLICITADA,Papel.RH,Papel.CONTABILIDADE,"Falta documento"));assertThrows(RegraNegocioException.class,()->validar(p,StatusPendencia.CORRECAO_SOLICITADA,Papel.FUNCIONARIO,Papel.CONTABILIDADE,"Falta documento"));}
 @Test void reenvioVoltaAoSolicitante(){var p=pendencia(StatusPendencia.CORRECAO_SOLICITADA,Papel.FUNCIONARIO);p.setSetorSolicitante(Papel.RH);assertDoesNotThrow(()->TransicaoStatus.validarReenvio(p,Set.of(Papel.FUNCIONARIO)));assertThrows(RegraNegocioException.class,()->TransicaoStatus.validarReenvio(p,Set.of(Papel.FINANCEIRO)));assertThrows(RegraNegocioException.class,()->validar(p,StatusPendencia.EM_ANALISE,Papel.RH,Papel.FUNCIONARIO,""));}
 @Test void concluirExigeAnaliseEOSetorAtual(){assertDoesNotThrow(()->validar(pendencia(StatusPendencia.EM_ANALISE,Papel.CONTABILIDADE),StatusPendencia.CONCLUIDA,Papel.CONTABILIDADE,Papel.CONTABILIDADE,""));assertThrows(RegraNegocioException.class,()->validar(pendencia(StatusPendencia.ABERTA,Papel.RH),StatusPendencia.CONCLUIDA,Papel.RH,Papel.RH,""));}
 @Test void cancelamentoExigeMotivoECriadorOuRh(){var p=pendencia(StatusPendencia.EM_ANALISE,Papel.CONTABILIDADE);assertDoesNotThrow(()->validar(p,StatusPendencia.CANCELADA,Papel.CONTABILIDADE,Papel.RH,"Cancelado"));assertThrows(RegraNegocioException.class,()->validar(p,StatusPendencia.CANCELADA,Papel.CONTABILIDADE,Papel.CONTABILIDADE,"Cancelado"));assertThrows(RegraNegocioException.class,()->validar(p,StatusPendencia.CANCELADA,Papel.RH,Papel.RH,""));}
 @Test void encerradasNaoPodemMudar(){for(var status:Set.of(StatusPendencia.CONCLUIDA,StatusPendencia.CANCELADA))assertThrows(RegraNegocioException.class,()->validar(pendencia(status,Papel.RH),StatusPendencia.CANCELADA,Papel.RH,Papel.RH,"Cancelar"));}
}
