import { Component,inject,provideAppInitializer,importProvidersFrom } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser'; import { provideRouter,RouterOutlet } from '@angular/router'; import { provideHttpClient,withInterceptors } from '@angular/common/http';
import { registerLocaleData } from '@angular/common'; import localePt from '@angular/common/locales/pt'; import { LOCALE_ID } from '@angular/core';
import { providePrimeNG } from 'primeng/config'; import { definePreset } from '@primeuix/themes'; import Aura from '@primeuix/themes/aura'; import { provideNgxMask } from 'ngx-mask';
import { LucideAngularModule,Workflow,UserRound,Building2,ArrowRight,ArrowUpRight,ShieldCheck,LayoutDashboard,ClipboardList,Clock3,Users,Files,Wallet,FileText,UserRoundCog,Settings,RotateCcw,LogOut,Menu,Search,CalendarDays,Bell,ChevronDown,X,MessageSquare,LockKeyhole,CircleCheck,Upload,Check,ScanSearch,Plus,CalendarClock,CircleAlert,Hand,Activity,Receipt,Info,ChevronLeft,ChevronRight,SlidersHorizontal,CloudUpload,FileCheck2,FilePlus2,Send,LogIn,Timer,Fingerprint,UserRoundPlus,Copy,Calculator,Download,Pencil } from 'lucide-angular';
import { routes } from './app/app.routes'; import { AuthService } from './app/core/auth/auth.service'; import { authInterceptor } from './app/core/auth/auth.interceptor'; import { API,RestApi } from './app/core/api/api.service';
registerLocaleData(localePt);
const tema=definePreset(Aura,{semantic:{primary:{50:'#eaf0fd',100:'#dbe6fc',200:'#bdcff8',300:'#8dacf0',400:'#5a85e8',500:'#2457d6',600:'#1c46b0',700:'#193c96',800:'#173477',900:'#152c61',950:'#0f1e3d'}}});
@Component({selector:'app-root',imports:[RouterOutlet],template:'<router-outlet />'})
class App {}
bootstrapApplication(App,{providers:[provideRouter(routes),provideHttpClient(withInterceptors([authInterceptor])),{provide:LOCALE_ID,useValue:'pt-BR'},provideNgxMask(),providePrimeNG({theme:{preset:tema,options:{darkModeSelector:false}},translation:{accept:'Sim',reject:'Não',emptyMessage:'Nenhum resultado encontrado'}}),{provide:API,useClass:RestApi},importProvidersFrom(LucideAngularModule.pick({Workflow,UserRound,Building2,ArrowRight,ArrowUpRight,ShieldCheck,LayoutDashboard,ClipboardList,Clock3,Users,Files,Wallet,FileText,UserRoundCog,Settings,RotateCcw,LogOut,Menu,Search,CalendarDays,Bell,ChevronDown,X,MessageSquare,LockKeyhole,CircleCheck,Upload,Check,ScanSearch,Plus,CalendarClock,CircleAlert,Hand,Activity,Receipt,Info,ChevronLeft,ChevronRight,SlidersHorizontal,CloudUpload,FileCheck2,FilePlus2,Send,LogIn,Timer,Fingerprint,UserRoundPlus,Copy,Calculator,Download,Pencil})),provideAppInitializer(()=>inject(AuthService).restaurar())]}).catch(erro=>console.error(erro));
