import { Component,DestroyRef,effect,inject,signal,untracked } from '@angular/core'; import { FormsModule } from '@angular/forms'; import { DatePipe,DecimalPipe } from '@angular/common'; import { DialogModule } from 'primeng/dialog';
import { API } from '../../core/api/api.service'; import { AuthService } from '../../core/auth/auth.service'; import { UiService } from '../../core/ui.service'; import { Ponto as Registro,Pendencia } from '../../core/models/modelos'; import { PageHeader } from '../../shared/components/page-header'; import { Icone } from '../../shared/components/icone'; import { Skeleton,EmptyState } from '../../shared/components/estados'; import { Avatar } from '../../shared/components/badges';
@Component({selector:'fc-ponto',imports:[FormsModule,DatePipe,DecimalPipe,DialogModule,PageHeader,Icone,Skeleton,EmptyState,Avatar],template:`
<fc-page-header [titulo]="funcionario?'Meu ponto':'Ponto da equipe'" [descricao]="funcionario?'Registre sua jornada e acompanhe as marcações do mês.':'Confira entradas, saídas e marcações que precisam de ajuste.'"/>
@if(funcionario){<section class="card clock-card"><div><span class="eyebrow">SUA JORNADA DE HOJE</span><h2>{{ui.hoje()|date:'EEEE, dd/MM/yyyy'}}</h2><div class="big-clock">{{agora()}}</div><p class="muted">{{registroHoje()?.saida?'Sua jornada foi encerrada.':registroHoje()?.entrada?'Entrada registrada. Ao terminar, registre sua saída.':'Pronto para começar o dia?'}}</p></div><div class="clock-action"><span class="clock-emblem"><fc-icon nome="clock-3" [tamanho]="40"/></span><button class="button primary" [disabled]="ocupado() || !!registroHoje()?.saida" (click)="registrar()"><fc-icon nome="fingerprint"/>{{registroHoje()?.saida?'Jornada encerrada':registroHoje()?.entrada?'Registrar saída':'Registrar entrada'}}</button><small>Marcação com horário do servidor.</small></div></section><div class="today-marks"><div class="card"><fc-icon nome="log-in"/><span>Entrada de hoje</span><strong>{{registroHoje()?.entrada?.slice(0,5)||'—'}}</strong></div><div class="card"><fc-icon nome="log-out"/><span>Saída de hoje</span><strong>{{registroHoje()?.saida?.slice(0,5)||'—'}}</strong></div><div class="card"><fc-icon nome="timer"/><span>Total registrado</span><strong>{{registroHoje()?.totalHoras||0|number:'1.2-2'}} h</strong></div></div>}
<section class="card"><div class="card-heading"><div><h2>{{funcionario?'Espelho do mês':'Marcações da equipe'}}</h2><p>{{ui.competencia()}} · {{funcionario?'Seu histórico de entradas e saídas':'Dias incompletos geram pendências para o RH'}}</p></div>@if(!funcionario){<label class="checkbox"><input type="checkbox" [(ngModel)]="inconsistentes" (ngModelChange)="carregar()"/>Só marcações incompletas</label>}</div>@if(carregando()){<fc-skeleton/>}@else if(erro()){<div class="error-state" role="alert">{{erro()}}<button class="button" (click)="carregar()">Tentar de novo</button></div>}@else if(!registros().length){<fc-empty titulo="Nenhuma marcação encontrada" [descricao]="funcionario?'Registre sua entrada para iniciar a jornada.':'Não há marcações incompletas neste período.'"/>}@else{<div class="table-scroll"><table class="data-table"><thead><tr>@if(!funcionario){<th>Funcionário</th>}<th>Dia</th><th>Entrada</th><th>Saída</th><th>Total</th><th>Horas extras</th><th>Situação</th>@if(!funcionario){<th>Ação</th>}</tr></thead><tbody>@for(p of registros();track p.funcionarioId+'-'+p.data){<tr [class.linha-incompleta]="p.inconsistente">@if(!funcionario){<td><div class="person"><fc-avatar [nome]="p.funcionarioNome" [pequeno]="true"/>{{p.funcionarioNome}}</div></td>}<td>{{p.data|date:'dd/MM/yyyy'}}</td><td>{{p.entrada?.slice(0,5)||'—'}}</td><td>{{p.saida?.slice(0,5)||'—'}}</td><td>{{p.totalHoras|number:'1.2-2'}} h</td><td>{{p.horasExtras|number:'1.2-2'}} h</td><td><span class="badge" [class.status-correcao_solicitada]="p.inconsistente" [class.status-concluida]="!p.inconsistente">{{p.inconsistente?'Marcação faltando':p.ajustado?'Ajustado':'Completo'}}</span></td>@if(!funcionario){<td><div class="row-actions">@if(p.id){<button class="button small" (click)="abrirAjuste(p)">Ajustar</button>}@if(p.inconsistente){<button class="text-button" [disabled]="ocupado()" (click)="criarPendencia(p)">Criar pendência</button>}</div></td>}</tr>}</tbody></table></div>}</section>
<p-dialog header="Ajustar marcação" [visible]="!!ajustando()" (visibleChange)="!$event && ajustando.set(null)" [modal]="true" [style]="{width:'480px',maxWidth:'96vw'}">@if(ajustando();as p){<p>{{p.funcionarioNome}} · {{p.data|date:'dd/MM/yyyy'}}</p><form (ngSubmit)="ajustar()"><div class="form-row"><label>Entrada<input type="time" name="entrada" [(ngModel)]="entrada" required/></label><label>Saída<input type="time" name="saida" [(ngModel)]="saida" required/></label></div><label>Justificativa obrigatória<textarea name="justificativa" [(ngModel)]="justificativa" rows="3" required maxlength="1000"></textarea></label><p class="muted">O ajuste fica registrado com seu nome, horário e justificativa.</p><button class="button primary" [disabled]="ocupado() || !justificativa.trim()">Salvar ajuste</button></form>}</p-dialog>`})
export class Ponto {
 readonly auth=inject(AuthService);readonly ui=inject(UiService);private api=inject(API);readonly funcionario=this.auth.setor()==='FUNCIONARIO';readonly registros=signal<Registro[]>([]);readonly carregando=signal(true);readonly ocupado=signal(false);readonly erro=signal('');readonly agora=signal('');readonly ajustando=signal<Registro|null>(null);inconsistentes=true;entrada='';saida='';justificativa='';
 constructor(){const atualizar=()=>this.agora.set(new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date()));atualizar();const timer=setInterval(atualizar,1000);inject(DestroyRef).onDestroy(()=>clearInterval(timer));effect(()=>{this.ui.competencia();this.ui.versao();untracked(()=>void this.carregar());});}
 registroHoje(){return this.registros().find(p=>p.data===this.ui.hoje());}
 async carregar(){this.carregando.set(true);this.erro.set('');try{this.registros.set(await this.api.get<Registro[]>(this.funcionario?'/ponto/me':'/ponto',{competencia:this.ui.competencia(),inconsistentes:this.funcionario?undefined:this.inconsistentes}));}catch(e){this.erro.set(this.ui.mensagem(e));}finally{this.carregando.set(false);}}
 async registrar(){this.ocupado.set(true);try{await this.api.post('/ponto/registrar');this.ui.competencia.set(this.ui.hoje().slice(0,7));await this.carregar();this.ui.avisar('Marcação registrada.');}catch(e){this.ui.falhar(e);}finally{this.ocupado.set(false);}}
 abrirAjuste(p:Registro){this.entrada=p.entrada?.slice(0,5)||'08:00';this.saida=p.saida?.slice(0,5)||'16:00';this.justificativa='';this.ajustando.set(p);}
 async ajustar(){this.ocupado.set(true);try{await this.api.patch(`/ponto/${this.ajustando()!.id}`,{entrada:this.entrada,saida:this.saida,justificativa:this.justificativa});this.ajustando.set(null);await this.carregar();this.ui.avisar('Ajuste salvo com justificativa no histórico.');}catch(e){this.ui.falhar(e);}finally{this.ocupado.set(false);}}
 async criarPendencia(p:Registro){this.ocupado.set(true);try{const pendencia=await this.api.post<Pendencia>('/pendencias',{funcionarioId:p.funcionarioId,titulo:'Marcação faltando em '+p.data,descricao:'Confira a entrada e saída de '+p.funcionarioNome+' no dia '+p.data+'.',tipo:'AJUSTE_PONTO',setorResponsavel:'RH',prazo:this.ui.hoje(),competencia:this.ui.competencia(),bloqueiaFolha:true});this.ui.atualizar();this.ui.abrirPendencia(pendencia.id);this.ui.avisar('Pendência de ponto criada.');}catch(e){this.ui.falhar(e);}finally{this.ocupado.set(false);}}
}
