import { Component,effect,inject,input,output,signal,untracked } from '@angular/core'; import { FormsModule } from '@angular/forms'; import { DatePipe } from '@angular/common'; import { DrawerModule } from 'primeng/drawer';
import { PendenciasRestApi } from '../../core/api/pendencias.api'; import { API } from '../../core/api/api.service'; import { AuthService } from '../../core/auth/auth.service'; import { UiService } from '../../core/ui.service';
import { Evento,Papel,Pendencia,StatusPendencia,tipos,setores } from '../../core/models/modelos'; import { Icone } from './icone'; import { StatusBadge,SetorBadge,Avatar } from './badges'; import { PrazoLabel } from './prazo-label'; import { Skeleton } from './estados';
@Component({selector:'fc-pendencia-drawer',imports:[FormsModule,DatePipe,DrawerModule,Icone,StatusBadge,SetorBadge,Avatar,PrazoLabel,Skeleton],template:`
<p-drawer [visible]="!!id()" (onHide)="fechar.emit()" position="right" [style]="{width:'480px',maxWidth:'100vw'}" [header]="'Detalhe da pendência'">
 @if(carregando()){<fc-skeleton/>}@else if(erro()){<div class="error-state" role="alert">{{erro()}}<button class="button" (click)="carregar(id()!)">Tentar de novo</button></div>}@else if(p();as item){
 <div class="drawer-content"><div class="detail-kicker"><span class="eyebrow">PENDÊNCIA #{{item.id.toString().padStart(3,'0')}}</span><fc-status [valor]="item.status"/></div><h2>{{item.titulo}}</h2><p class="muted">{{item.descricao}}</p>
 <div class="detail-owner"><fc-setor [valor]="item.setorResponsavel"/><fc-prazo [valor]="item.prazo" [atrasada]="item.atrasada"/></div>
 @if(item.bloqueiaFolha && item.status!=='CONCLUIDA' && item.status!=='CANCELADA'){<div class="notice warning"><fc-icon nome="lock-keyhole"/>Esta pendência bloqueia a folha de {{item.competencia}}.</div>}
 @if(item.abonado){<div class="notice success"><fc-icon nome="circle-check"/>Afastamento aprovado pelo RH. Dias abonados no cálculo.</div>}
 <dl class="detail-data"><dt>Funcionário</dt><dd>{{item.funcionarioNome}}</dd><dt>Tipo</dt><dd>{{tipos[item.tipo]}}</dd><dt>Criada em</dt><dd>{{item.criadoEm | date:'dd/MM/yyyy HH:mm'}}</dd><dt>Criada por</dt><dd>{{item.criadoPor}}</dd><dt>Responsável</dt><dd>{{item.responsavelNome || setores[item.setorResponsavel]}}</dd>@if(item.dataInicio){<dt>Período</dt><dd>{{item.dataInicio|date:'dd/MM'}} a {{item.dataFim|date:'dd/MM/yyyy'}}</dd>}</dl>
 @if(item.documentos.length){<h3>Documentos</h3>@for(documento of item.documentos;track documento.id){<div class="document-card"><fc-icon nome="file-text" [tamanho]="28"/><div><strong>{{documento.nomeOriginal}}</strong><small>{{(documento.tamanhoBytes/1024).toFixed(0)}} KB · {{documento.sensivel?'Acesso restrito ao RH e titular':'Documento'}}</small></div><button class="button" (click)="visualizar(documento.id)">Visualizar</button></div>}}
 @if(item.tipo==='ATESTADO' && !item.documentos.length && !auth.tem('RH','FUNCIONARIO')){<div class="notice neutral"><fc-icon nome="shield-check"/>Documento de saúde restrito. O resultado da análise aparece acima.</div>}
 @if(auth.setor()==='RH' && item.status!=='CONCLUIDA' && item.status!=='CANCELADA'){<details class="assign"><summary>Ajustar responsável e prazo</summary><label>Setor responsável<select [(ngModel)]="novoSetor">@for(setor of papeis;track setor){<option [value]="setor">{{setores[setor]}}</option>}</select></label><label>Prazo<input type="date" [(ngModel)]="novoPrazo" [min]="ui.hoje()"/></label><button class="button" [disabled]="ocupado()" (click)="atribuir()">Salvar alterações</button></details>}
 <div class="section-heading"><h3>Histórico da pendência</h3><span class="muted">{{eventos().length}} eventos</span></div><div class="timeline">@for(evento of eventos();track evento.id){<div class="timeline-event"><fc-avatar [nome]="evento.autor" [setor]="evento.papeis[0]" [pequeno]="true"/><div><strong>{{evento.autor}}</strong><time>{{evento.criadoEm | date:'dd/MM/yyyy · HH:mm'}}</time><p>{{evento.comentario}}</p>@if(evento.tipo==='STATUS_ALTERADO'){<small>{{evento.statusNovo ? nomesStatus(evento.statusNovo) : ''}}</small>}</div></div>}</div>
 @if(auth.setor()!=='ADMIN'){<label>Comentário<textarea [(ngModel)]="comentario" maxlength="4000" rows="3" placeholder="Escreva uma atualização ou explique a correção..."></textarea></label><button class="button" [disabled]="ocupado() || !comentario.trim()" (click)="comentar()"><fc-icon nome="message-square"/>Adicionar comentário</button>}
 @if(item.status==='CORRECAO_SOLICITADA' && comigo(item) && auth.tem('FUNCIONARIO','RH')){<div class="notice warning">Envie o documento corrigido para retomar a análise.</div><label class="file-button"><fc-icon nome="upload"/>Reenviar documento<input type="file" accept=".pdf,.png,.jpg,.jpeg" (change)="reenviar($event)" [disabled]="ocupado()"/></label>}
 </div>
 <div class="drawer-actions">@if(comigo(item) && item.status==='ABERTA' && auth.setor()!=='FUNCIONARIO' && auth.setor()!=='ADMIN'){<button class="button primary" [disabled]="ocupado()" (click)="mudar('EM_ANALISE',item.setorResponsavel,'Análise iniciada.')"><fc-icon nome="scan-search"/>Iniciar análise</button>}
 @if(comigo(item) && item.status==='EM_ANALISE' && auth.setor()!=='ADMIN'){
  @if(auth.setor()==='RH'){<button class="button primary" [disabled]="ocupado()" (click)="mudar('EM_ANALISE','CONTABILIDADE','Aprovado pelo RH e enviado à Contabilidade.')"><fc-icon nome="check"/>Aprovar e encaminhar</button>}
  @if(auth.setor()!=='FUNCIONARIO'){<button class="button" [disabled]="ocupado()" (click)="mudar('CORRECAO_SOLICITADA',auth.setor()==='CONTABILIDADE'?'RH':'FUNCIONARIO',comentario,true)">Solicitar correção</button><button class="button" [disabled]="ocupado()" (click)="mudar('CONCLUIDA',item.setorResponsavel,comentario || 'Pendência concluída.')">Concluir</button>}
 }@if((auth.setor()==='RH' || item.criadoPor===auth.usuario()?.nome) && item.status!=='CONCLUIDA' && item.status!=='CANCELADA'){<button class="text-button danger" [disabled]="ocupado()" (click)="mudar('CANCELADA',item.setorResponsavel,comentario,true)">Cancelar</button>}</div>
 }
</p-drawer>`})
export class PendenciaDrawer {
 readonly id=input<number|null>(null); readonly fechar=output<void>(); readonly mudou=output<void>();
 readonly p=signal<Pendencia|null>(null); readonly eventos=signal<Evento[]>([]); readonly carregando=signal(false); readonly ocupado=signal(false); readonly erro=signal('');
 readonly auth=inject(AuthService); readonly ui=inject(UiService); private api=inject(API); private pendencias=inject(PendenciasRestApi); readonly tipos=tipos; readonly setores=setores; readonly papeis:Papel[]=['FUNCIONARIO','RH','FINANCEIRO','CONTABILIDADE'];
 comentario=''; novoSetor:Papel='RH'; novoPrazo='';
 constructor(){effect(()=>{const id=this.id();if(id)untracked(()=>void this.carregar(id));});}
 async carregar(id:number){this.carregando.set(true);this.erro.set('');this.comentario='';try{const [p,eventos]=await Promise.all([this.pendencias.detalhe(id),this.pendencias.historico(id)]);this.p.set(p);this.eventos.set(eventos);this.novoSetor=p.setorResponsavel;this.novoPrazo=p.prazo;}catch(e){this.erro.set(this.ui.mensagem(e));}finally{this.carregando.set(false);}}
 comigo(p:Pendencia){return this.auth.setor()===p.setorResponsavel;}
 nomesStatus(valor:StatusPendencia){return {ABERTA:'Aberta',EM_ANALISE:'Em análise',CORRECAO_SOLICITADA:'Correção solicitada',CONCLUIDA:'Concluída',CANCELADA:'Cancelada'}[valor];}
 async mudar(status:StatusPendencia,setor:Papel,comentario:string,exigir=false){if(exigir&&!comentario.trim()){this.ui.avisar('Explique o motivo no campo de comentário.');return;}this.ocupado.set(true);try{await this.pendencias.status(this.id()!,status,setor,comentario);await this.carregar(this.id()!);this.mudou.emit();this.ui.avisar(status==='EM_ANALISE'&&setor==='CONTABILIDADE'?'Atestado aprovado e enviado à Contabilidade.':'Pendência atualizada.');}catch(e){this.ui.falhar(e);}finally{this.ocupado.set(false);}}
 async comentar(){this.ocupado.set(true);try{await this.pendencias.comentar(this.id()!,this.comentario);await this.carregar(this.id()!);this.mudou.emit();this.ui.avisar('Comentário registrado no histórico.');}catch(e){this.ui.falhar(e);}finally{this.ocupado.set(false);}}
 async atribuir(){this.ocupado.set(true);try{await this.api.patch(`/pendencias/${this.id()}`,{setorResponsavel:this.novoSetor,prazo:this.novoPrazo});await this.carregar(this.id()!);this.mudou.emit();this.ui.avisar('Responsável e prazo atualizados.');}catch(e){this.ui.falhar(e);}finally{this.ocupado.set(false);}}
 async visualizar(id:number){try{await this.ui.baixar(await this.api.arquivo(`/documentos/${id}/arquivo`),'documento.pdf',true);}catch(e){this.ui.falhar(e);}}
 async reenviar(evento:Event){const arquivo=(evento.target as HTMLInputElement).files?.[0];if(!arquivo)return;if(arquivo.size>5*1024*1024){this.ui.avisar('O arquivo deve ter até 5 MB.');return;}this.ocupado.set(true);try{await this.pendencias.anexar(this.id()!,arquivo);await this.carregar(this.id()!);this.mudou.emit();this.ui.avisar('Documento reenviado para análise.');}catch(e){this.ui.falhar(e);}finally{this.ocupado.set(false);}}
}
